export interface BottomCardTemplate {
  id: string;
  name: string;
  category: 'kawaii' | 'y2k' | 'polaroid' | 'dreamy' | 'romantic' | 'friendship' | 'minimal' | 'scrapbook';
  
  // Visual Styles
  backgroundType: 'solid' | 'gradient' | 'glass';
  backgroundColor: string; // solid color (hex) or gradient CSS value (canvas format friendly)
  fontFamily: 'Fredoka' | 'VT323' | 'Space Grotesk' | 'Inter' | 'Pacifico';
  textColor: string; // hex color for drawing
  borderColor: string; // hex color for drawing
  borderStyle: 'solid' | 'dashed' | 'double' | 'none';
  borderRadius: 'none' | 'md' | 'xl' | '3xl' | 'full'; // mapping to visual looks
  glowColor?: string; // hex
  opacity: number; // 0.1 to 1.0
  
  // Custom text overlays
  caption: string;
  subCaption?: string;
  brandingText: string; // optional creator signature
  showBranding: boolean;
  
  // Cute decorations
  stickers: string[]; // base list, e.g. ['🎀', '💖']
  stickerPositions: 'sides' | 'corners' | 'scattered' | 'top_fringe';
  
  // Extra elements
  ribbonId?: string;
  ribbonPlacement?: 'left' | 'right' | 'center' | 'none';
  hasGlitter?: boolean;
  hasSway?: boolean;
  hasShadow?: boolean;
  hasGlow?: boolean;
  dateFormat?: 'retro' | 'simple' | 'none';
  isTrending?: boolean;
}

export const BOTTOM_CARD_CATEGORIES = [
  { id: 'all', name: '✨ All Styles', emoji: '🌈' },
  { id: 'kawaii', name: '🧸 Kawaii Cute', emoji: '🧸' },
  { id: 'y2k', name: '💿 Y2K Chrome', emoji: '⚡' },
  { id: 'polaroid', name: '📸 Polaroid Film', emoji: '🎞️' },
  { id: 'dreamy', name: '☁️ Dreamy Fairy', emoji: '☁️' },
  { id: 'romantic', name: '💖 Romantic Blush', emoji: '💌' },
  { id: 'friendship', name: '👯 Bestie Vibe', emoji: '👭' },
  { id: 'minimal', name: '🪐 Minimal Glass', emoji: '💎' },
  { id: 'scrapbook', name: '✂️ Scrapbook Zine', emoji: '🎨' }
];

// Generate 100+ highly beautiful, categorized templates
export const PRESET_BOTTOM_CARDS: BottomCardTemplate[] = [
  // --- KAWAII CUTE (14 templates) ---
  {
    id: 'k_teddy_love',
    name: '🧸 Teddy Bear Tea Party',
    category: 'kawaii',
    backgroundType: 'gradient',
    backgroundColor: 'linear-gradient(180deg, #fffbeb 0%, #fef3c7 100%)',
    fontFamily: 'Fredoka',
    textColor: '#92400e',
    borderColor: '#f59e0b',
    borderStyle: 'solid',
    borderRadius: 'xl',
    opacity: 1.0,
    caption: '🧸 TEA FOR TWO & ME & YOU 🍯',
    subCaption: 'Warm Honey Hugs',
    brandingText: 'Made with 💖 by Arpita',
    showBranding: true,
    stickers: ['🧸', '🍯', '🍪'],
    stickerPositions: 'sides',
    isTrending: true
  },
  {
    id: 'k_bunny_ears',
    name: '🐰 Jelly Bean Bunny',
    category: 'kawaii',
    backgroundType: 'solid',
    backgroundColor: '#fff1f2',
    fontFamily: 'Pacifico',
    textColor: '#be123c',
    borderColor: '#fda4af',
    borderStyle: 'dashed',
    borderRadius: 'full',
    opacity: 1.0,
    caption: '🐰 HOPPING THROUGH CLOUDS ✨',
    subCaption: 'Fluffy Cotton Tail Days',
    brandingText: 'Captured on Arpita Snaps • 🎀',
    showBranding: true,
    stickers: ['🐰', '🍓', '🧁'],
    stickerPositions: 'scattered'
  },
  {
    id: 'k_nyan_cat',
    name: '🐱 Marshmallow Meow',
    category: 'kawaii',
    backgroundType: 'gradient',
    backgroundColor: 'linear-gradient(135deg, #fef2f2 0%, #fff1f2 100%)',
    fontFamily: 'Fredoka',
    textColor: '#e11d48',
    borderColor: '#fb7185',
    borderStyle: 'solid',
    borderRadius: '3xl',
    opacity: 1.0,
    caption: '🐾 PERFECTLY PURR-FECT MEMORY 🐱',
    subCaption: 'Soft paws and pink noses',
    brandingText: 'Created in Cute Space ✨',
    showBranding: true,
    stickers: ['🐱', '🌸', '🩰'],
    stickerPositions: 'corners'
  },
  {
    id: 'k_hearts_galore',
    name: '💖 Double Bubble Blush',
    category: 'kawaii',
    backgroundType: 'gradient',
    backgroundColor: 'linear-gradient(180deg, #ffe4e6 0%, #fecdd3 100%)',
    fontFamily: 'Fredoka',
    textColor: '#db2777',
    borderColor: '#fda4af',
    borderStyle: 'double',
    borderRadius: '3xl',
    opacity: 1.0,
    caption: '💘 SWEETER THAN SUGAR CANDY 💘',
    subCaption: 'Blowing heart-shaped bubbles',
    brandingText: 'Captured on Arpita Snaps ✨',
    showBranding: true,
    stickers: ['💖', '💌', '🍬'],
    stickerPositions: 'top_fringe',
    isTrending: true
  },
  {
    id: 'k_pink_ribbon',
    name: '🎀 Classic Satin Bow',
    category: 'kawaii',
    backgroundType: 'solid',
    backgroundColor: '#fff5f7',
    fontFamily: 'Fredoka',
    textColor: '#db2777',
    borderColor: '#ffccd5',
    borderStyle: 'solid',
    borderRadius: 'xl',
    opacity: 1.0,
    caption: '🎀 ALWAYS TIED WITH A BOW 🎀',
    subCaption: 'Princess Balletcore Vibes',
    brandingText: 'Made with 💖 by Arpita',
    showBranding: true,
    stickers: ['🎀', '🩰', '🕊️'],
    stickerPositions: 'sides'
  },
  {
    id: 'k_pastel_candy',
    name: '🍬 Cotton Candy Corner',
    category: 'kawaii',
    backgroundType: 'gradient',
    backgroundColor: 'linear-gradient(90deg, #ffd1dc 0%, #d1f7ff 100%)',
    fontFamily: 'Fredoka',
    textColor: '#701a75',
    borderColor: '#ffccd5',
    borderStyle: 'none',
    borderRadius: '3xl',
    opacity: 1.0,
    caption: '🍬 SWEET CANDY RAINBOWS 🌈',
    subCaption: 'Dreamy sugar glaze rush',
    brandingText: 'Captured on Arpita Snaps ✨',
    showBranding: true,
    stickers: ['🍭', '🍬', '🍒'],
    stickerPositions: 'scattered'
  },
  {
    id: 'k_cloud_fluff',
    name: '☁️ Floating Meringue Sky',
    category: 'kawaii',
    backgroundType: 'gradient',
    backgroundColor: 'linear-gradient(180deg, #f0fdf4 0%, #e0f2fe 100%)',
    fontFamily: 'Fredoka',
    textColor: '#0369a1',
    borderColor: '#bae6fd',
    borderStyle: 'solid',
    borderRadius: 'xl',
    opacity: 0.95,
    caption: '☁️ FLOATING ON MERINGUE CLOUDS ☁️',
    subCaption: 'Softest dreams up high',
    brandingText: 'Made with 💖 by Arpita',
    showBranding: true,
    stickers: ['☁️', '🎈', '⭐'],
    stickerPositions: 'corners'
  },
  {
    id: 'k_chibi_doodle',
    name: '🎨 Little Chibi Sketchbook',
    category: 'kawaii',
    backgroundType: 'solid',
    backgroundColor: '#fafaf9',
    fontFamily: 'Pacifico',
    textColor: '#1c1917',
    borderColor: '#d6d3d1',
    borderStyle: 'solid',
    borderRadius: 'md',
    opacity: 1.0,
    caption: '✨ Tiny doodles on my margin ✨',
    subCaption: 'Chibi stars & smiley faces',
    brandingText: 'Artist signature: Arpita Snaps',
    showBranding: true,
    stickers: ['🐣', '✏️', '🌱'],
    stickerPositions: 'sides'
  },
  {
    id: 'k_frog_puddle',
    name: '🐸 Lilypad Puddle hop',
    category: 'kawaii',
    backgroundType: 'gradient',
    backgroundColor: 'linear-gradient(135deg, #f0fdf4 0%, #dcfce7 100%)',
    fontFamily: 'Fredoka',
    textColor: '#15803d',
    borderColor: '#86efac',
    borderStyle: 'solid',
    borderRadius: 'xl',
    opacity: 1.0,
    caption: '🐸 HOPPY TIMES WITH MY BES-TOAD 🌟',
    subCaption: 'Splish splash sweet green days',
    brandingText: 'Captured on Arpita Snaps',
    showBranding: true,
    stickers: ['🐸', '🍀', '🌂'],
    stickerPositions: 'sides'
  },
  {
    id: 'k_strawberry_jam',
    name: '🍓 Sweet Strawberry Shortcake',
    category: 'kawaii',
    backgroundType: 'solid',
    backgroundColor: '#fff5f5',
    fontFamily: 'Fredoka',
    textColor: '#c53030',
    borderColor: '#feb2b2',
    borderStyle: 'dashed',
    borderRadius: 'full',
    opacity: 1.0,
    caption: '🍓 FRESHLY PICKED SWEETNESS 🍰',
    subCaption: 'Whipped cream and berry kisses',
    brandingText: 'Made with 💖 by Arpita',
    showBranding: true,
    stickers: ['🍓', '🍰', '🌸'],
    stickerPositions: 'scattered'
  },
  {
    id: 'k_sparkle_bubble',
    name: '🫧 Shiny Bubble Princess',
    category: 'kawaii',
    backgroundType: 'gradient',
    backgroundColor: 'linear-gradient(180deg, #fdf4ff 0%, #fae8ff 100%)',
    fontFamily: 'Fredoka',
    textColor: '#a21caf',
    borderColor: '#f0abfc',
    borderStyle: 'double',
    borderRadius: '3xl',
    opacity: 1.0,
    caption: '🫧 SPINNING IN SHINY BUBBLES 🫧',
    subCaption: 'Iridescent princess aura',
    brandingText: 'Captured on Arpita Snaps ✨',
    showBranding: false,
    stickers: ['🫧', '🐳', '✨'],
    stickerPositions: 'sides'
  },
  {
    id: 'k_cute_dinosaur',
    name: '🦖 Mini Dino Jungle',
    category: 'kawaii',
    backgroundType: 'solid',
    backgroundColor: '#f6ffed',
    fontFamily: 'VT323',
    textColor: '#389e0d',
    borderColor: '#b7eb8f',
    borderStyle: 'solid',
    borderRadius: 'xl',
    opacity: 1.0,
    caption: '🦖 RAWR MEANS I LOVE YOU IN DINO 🌋',
    subCaption: 'Prehistoric sweet snuggle session',
    brandingText: 'Made with 💖 by Arpita',
    showBranding: true,
    stickers: ['🦖', '🌴', '⭐'],
    stickerPositions: 'corners'
  },
  {
    id: 'k_pompom_cute',
    name: '🍮 Caramel Pudding Roll',
    category: 'kawaii',
    backgroundType: 'gradient',
    backgroundColor: 'linear-gradient(180deg, #fffbeb 0%, #fff7ed 100%)',
    fontFamily: 'Fredoka',
    textColor: '#854d0e',
    borderColor: '#fed7aa',
    borderStyle: 'solid',
    borderRadius: 'xl',
    opacity: 1.0,
    caption: '🍮 SWEET CARAMEL PUDDING DREAMS 🍮',
    subCaption: 'Custard bounces & creamy glaze',
    brandingText: 'Captured on Arpita Snaps ✨',
    showBranding: true,
    stickers: ['🍮', '🍒', '🍯'],
    stickerPositions: 'sides'
  },
  {
    id: 'k_angel_wings',
    name: '👼 Little Cherub Cloud',
    category: 'kawaii',
    backgroundType: 'solid',
    backgroundColor: '#f0f9ff',
    fontFamily: 'Fredoka',
    textColor: '#0284c7',
    borderColor: '#e0f2fe',
    borderStyle: 'solid',
    borderRadius: 'full',
    opacity: 1.0,
    caption: '👼 SENT DIRECTLY FROM CUTE HEAVEN 👼',
    subCaption: 'Angel feathers and harp bells',
    brandingText: 'Made with 💖 by Arpita',
    showBranding: true,
    stickers: ['👼', '☁️', '💖'],
    stickerPositions: 'top_fringe'
  },

  // --- Y2K CHROME & GLITTER (13 templates) ---
  {
    id: 'y_retro_chrome',
    name: '💿 Liquid Chrome Wave',
    category: 'y2k',
    backgroundType: 'gradient',
    backgroundColor: 'linear-gradient(135deg, #f1f5f9 0%, #cbd5e1 50%, #94a3b8 100%)',
    fontFamily: 'Space Grotesk',
    textColor: '#1e293b',
    borderColor: '#475569',
    borderStyle: 'solid',
    borderRadius: 'none',
    opacity: 1.0,
    caption: '💿 METALLIC LIQUID CHROME CORE 💿',
    subCaption: 'SYSTEM DECO RUNNING FINE',
    brandingText: 'CONSOLE_SIGNATURE: ARPITA_SNAPS',
    showBranding: true,
    stickers: ['💿', '🪐', '💫'],
    stickerPositions: 'corners',
    isTrending: true
  },
  {
    id: 'y_pink_metallic',
    name: '⚡ Cyber Barbie Hot Metal',
    category: 'y2k',
    backgroundType: 'gradient',
    backgroundColor: 'linear-gradient(90deg, #ec4899 0%, #be185d 100%)',
    fontFamily: 'Space Grotesk',
    textColor: '#ffffff',
    borderColor: '#fbcfe8',
    borderStyle: 'double',
    borderRadius: 'none',
    opacity: 1.0,
    caption: '⚡ CYBER PINK MATRIX EXTREME ⚡',
    subCaption: 'HOT SHINE LIQUID DIAMOND',
    brandingText: 'CAPTURED BY ARPITA',
    showBranding: true,
    stickers: ['⚡', '💅', '👑'],
    stickerPositions: 'sides',
    glowColor: '#ec4899',
    isTrending: true
  },
  {
    id: 'y_myspace_04',
    name: '👾 MySpace CSS Glitter',
    category: 'y2k',
    backgroundType: 'solid',
    backgroundColor: '#000000',
    fontFamily: 'VT323',
    textColor: '#39ff14',
    borderColor: '#39ff14',
    borderStyle: 'dashed',
    borderRadius: 'md',
    opacity: 1.0,
    caption: '★ ADD ME TO YOUR TOP 8 BESTIES ★',
    subCaption: 'Web design is my true passion',
    brandingText: 'Profile coded by Arpita',
    showBranding: true,
    stickers: ['👾', '💾', '🎸'],
    stickerPositions: 'scattered'
  },
  {
    id: 'y_hologram_glass',
    name: '🔮 Iridescent Holo Visor',
    category: 'y2k',
    backgroundType: 'gradient',
    backgroundColor: 'linear-gradient(135deg, #e0f2fe 0%, #fdf2f8 50%, #e0e7ff 100%)',
    fontFamily: 'Space Grotesk',
    textColor: '#3730a3',
    borderColor: '#818cf8',
    borderStyle: 'solid',
    borderRadius: '3xl',
    opacity: 0.9,
    caption: '🌌 HOLOGRAM FLUID AURA DECK 🌌',
    subCaption: 'Prismatic diffraction feedback',
    brandingText: 'Captured on Arpita Snaps ✨',
    showBranding: false,
    stickers: ['🔮', '🛸', '🛰️'],
    stickerPositions: 'corners'
  },
  {
    id: 'y_glitter_bling',
    name: '✨ Bling Bling Diamond',
    category: 'y2k',
    backgroundType: 'gradient',
    backgroundColor: 'linear-gradient(90deg, #ffc9e4 0%, #ffeaa7 50%, #b3f2ff 100%)',
    fontFamily: 'Fredoka',
    textColor: '#701a75',
    borderColor: '#f472b6',
    borderStyle: 'solid',
    borderRadius: 'xl',
    opacity: 1.0,
    caption: '✨ DIAMOND QUEEN GLITTER CRUSH ⭐',
    subCaption: 'Brighter than a disco spotlight',
    brandingText: 'Made with 💖 by Arpita',
    showBranding: true,
    stickers: ['✨', '💎', '💄'],
    stickerPositions: 'top_fringe',
    hasGlitter: true
  },
  {
    id: 'y_retro_webcam',
    name: '📹 1999 Digicam Stamp',
    category: 'y2k',
    backgroundType: 'solid',
    backgroundColor: '#111827',
    fontFamily: 'VT323',
    textColor: '#ff7115',
    borderColor: '#374151',
    borderStyle: 'solid',
    borderRadius: 'none',
    opacity: 1.0,
    caption: '📹 LIVE VIDEO STREAM RE_PLAY [04:20:00] 📼',
    subCaption: 'DIGITAL WEBCAM CAPTURE - LED IMPRINT',
    brandingText: 'SYSTEM_STAMP: ARPITA_SNAPS',
    showBranding: true,
    stickers: ['📟', '📼', '📹'],
    stickerPositions: 'sides'
  },
  {
    id: 'y_pixel_arcade',
    name: '🎮 8-Bit Game Center',
    category: 'y2k',
    backgroundType: 'solid',
    backgroundColor: '#2d1b4e',
    fontFamily: 'VT323',
    textColor: '#f43f5e',
    borderColor: '#ec4899',
    borderStyle: 'solid',
    borderRadius: 'md',
    opacity: 1.0,
    caption: '🎮 INSERT COIN TO RESTART CUTE SESSION 👾',
    subCaption: 'Level 99 Bestie Powerup Complete',
    brandingText: 'Dev Team: Arpita Snaps 🕹️',
    showBranding: true,
    stickers: ['🎮', '👾', '🔥'],
    stickerPositions: 'corners'
  },
  {
    id: 'y_cyber_goth',
    name: '⛓️ Neon Venom Tribal',
    category: 'y2k',
    backgroundType: 'solid',
    backgroundColor: '#090d16',
    fontFamily: 'Space Grotesk',
    textColor: '#a855f7',
    borderColor: '#7c3aed',
    borderStyle: 'dashed',
    borderRadius: 'none',
    opacity: 1.0,
    caption: '⛓️ LIQUID CYAN CYBERNETIC WEB 🌑',
    subCaption: 'Virtual glitch pulse response',
    brandingText: 'Captured on Arpita Snaps',
    showBranding: true,
    stickers: ['🐈‍⬛', '💀', '👽'],
    stickerPositions: 'sides',
    glowColor: '#7c3aed'
  },
  {
    id: 'y_win98_pop',
    name: '💻 Win98 Cute Desktop',
    category: 'y2k',
    backgroundType: 'solid',
    backgroundColor: '#008080',
    fontFamily: 'VT323',
    textColor: '#ffffff',
    borderColor: '#dfdfdf',
    borderStyle: 'double',
    borderRadius: 'md',
    opacity: 1.0,
    caption: '💾 SYSTEM ERROR: TOO MUCH CUTENESS DETECTED 💻',
    subCaption: 'C:\\Desktop\\Besties\\snaps.png',
    brandingText: 'Windows 95/98 Elite Platform • Arpita',
    showBranding: true,
    stickers: ['💾', '🖱️', '📂'],
    stickerPositions: 'corners'
  },
  {
    id: 'y_tamagotchi',
    name: '📟 Tamagotchi Pocket Pet',
    category: 'y2k',
    backgroundType: 'gradient',
    backgroundColor: 'linear-gradient(180deg, #ffedfa 0%, #ffd1e8 100%)',
    fontFamily: 'Fredoka',
    textColor: '#c026d3',
    borderColor: '#f472b6',
    borderStyle: 'solid',
    borderRadius: '3xl',
    opacity: 1.0,
    caption: '📟 MY HAPPY POCKET CHIBI PET 📟',
    subCaption: 'Feed sweets, clean up stars, tap buttons',
    brandingText: 'Pocket Game by Arpita Snaps',
    showBranding: true,
    stickers: ['📟', '🐣', '🍬'],
    stickerPositions: 'sides'
  },
  {
    id: 'y_glitch_vibe',
    name: '📺 VHS Tracking Lost',
    category: 'y2k',
    backgroundType: 'gradient',
    backgroundColor: 'linear-gradient(135deg, #020617 0%, #172554 100%)',
    fontFamily: 'Space Grotesk',
    textColor: '#22d3ee',
    borderColor: '#06b6d4',
    borderStyle: 'double',
    borderRadius: 'none',
    opacity: 1.0,
    caption: '📺 TRACKING LOST ... AUTO PLAYING 📼',
    subCaption: 'BFF MEMORY CAPTURED ON HI-FI MAGNETIC TAPE',
    brandingText: 'Arpita Snaps VHS Rec Co.',
    showBranding: true,
    stickers: ['📺', '📼', '🛰️'],
    stickerPositions: 'scattered'
  },
  {
    id: 'y_rave_neon',
    name: '🌌 Techno Rave Underworld',
    category: 'y2k',
    backgroundType: 'solid',
    backgroundColor: '#000000',
    fontFamily: 'Space Grotesk',
    textColor: '#22c55e',
    borderColor: '#22c55e',
    borderStyle: 'solid',
    borderRadius: 'xl',
    opacity: 1.0,
    caption: '🔊 PLUR: PEACE LOVE UNITY RESPECT 🌌',
    subCaption: 'Neon rave pulse in 135BPM techno',
    brandingText: 'Rave Club Card by Arpita Snaps',
    showBranding: true,
    stickers: ['👽', '🔊', '⚡'],
    stickerPositions: 'sides',
    glowColor: '#22c55e'
  },
  {
    id: 'y_cyber_princess',
    name: '👑 Cyber Cutie Diadem',
    category: 'y2k',
    backgroundType: 'gradient',
    backgroundColor: 'linear-gradient(45deg, #ffd6e7 0%, #e8d5ff 100%)',
    fontFamily: 'Fredoka',
    textColor: '#8b5cf6',
    borderColor: '#c084fc',
    borderStyle: 'solid',
    borderRadius: '3xl',
    opacity: 1.0,
    caption: '👑 CYBER PRINCESS EXCLUSIVE VIP STATUS 👑',
    subCaption: 'Wearing shiny crown on my virtual screen',
    brandingText: 'Captured on Arpita Snaps ✨',
    showBranding: true,
    stickers: ['👑', '✨', '🦄'],
    stickerPositions: 'corners'
  },

  // --- POLAROID & RETRO (13 templates) ---
  {
    id: 'p_vintage_polaroid',
    name: '🎞️ 1970s Instant Photo Frame',
    category: 'polaroid',
    backgroundType: 'solid',
    backgroundColor: '#fbfbf8',
    fontFamily: 'Inter',
    textColor: '#2d3748',
    borderColor: '#e2e8f0',
    borderStyle: 'solid',
    borderRadius: 'none',
    opacity: 1.0,
    caption: '🎞️ MEMORIES DESERVE TO BE PRINTED IN PHOTO 🎞️',
    subCaption: 'May index card No. 248',
    brandingText: 'Captured on Arpita Snaps • Polaroid System',
    showBranding: true,
    stickers: ['🎞️', '📸', '✏️'],
    stickerPositions: 'corners',
    isTrending: true
  },
  {
    id: 'p_worn_paper',
    name: '✂️ Torn Scrapbook Memo Card',
    category: 'polaroid',
    backgroundType: 'solid',
    backgroundColor: '#faf6eb',
    fontFamily: 'Pacifico',
    textColor: '#473c2a',
    borderColor: '#ddcfb4',
    borderStyle: 'dashed',
    borderRadius: 'none',
    opacity: 1.0,
    caption: '✨ Left on my desktop as a lovely memory',
    subCaption: 'Torn edges and coffee stain circles',
    brandingText: 'Saved with love by Arpita',
    showBranding: true,
    stickers: ['📰', '✂️', '☕'],
    stickerPositions: 'sides'
  },
  {
    id: 'p_beige_aesthetic',
    name: '☕ Warm Coffee Cozy Mug',
    category: 'polaroid',
    backgroundType: 'gradient',
    backgroundColor: 'linear-gradient(180deg, #f7efe5 0%, #efe1d1 100%)',
    fontFamily: 'Inter',
    textColor: '#6f4e37',
    borderColor: '#d2b48c',
    borderStyle: 'solid',
    borderRadius: 'xl',
    opacity: 1.0,
    caption: '☕ WARM CARAMEL MACCHIATO DAYS 🍂',
    subCaption: 'Sipping cinnamon cookies and laughing loud',
    brandingText: 'Captured on Arpita Snaps ✨',
    showBranding: true,
    stickers: ['☕', '🥐', '🍂'],
    stickerPositions: 'sides'
  },
  {
    id: 'p_film_strip_black',
    name: '🎬 Noir Cinematic negatives',
    category: 'polaroid',
    backgroundType: 'solid',
    backgroundColor: '#020202',
    fontFamily: 'Space Grotesk',
    textColor: '#f3f4f6',
    borderColor: '#1f2937',
    borderStyle: 'solid',
    borderRadius: 'none',
    opacity: 1.0,
    caption: '🎬 RETRO FILM NEGATIVE ARCHIVE NO. 400TX 🎬',
    subCaption: 'BFF EDITORIAL CELLULOID SHOT',
    brandingText: 'CINE_FRAME_CO: ARPITA_SNAPS',
    showBranding: true,
    stickers: ['🎬', '📼', '📷'],
    stickerPositions: 'corners'
  },
  {
    id: 'p_journal_note',
    name: '📝 Handwritten Diary Margin',
    category: 'polaroid',
    backgroundType: 'solid',
    backgroundColor: '#ffffff',
    fontFamily: 'Pacifico',
    textColor: '#1d4ed8', // classic blue ink pen Look
    borderColor: '#e5e7eb',
    borderStyle: 'none',
    borderRadius: 'md',
    opacity: 1.0,
    caption: 'We laughed so hard this afternoon! Memories of lifetime...',
    subCaption: 'Written in blue fountain ink',
    brandingText: 'Made with 💖 by Arpita',
    showBranding: true,
    stickers: ['📝', '💭', '🎀'],
    stickerPositions: 'scattered'
  },
  {
    id: 'p_warm_cabin',
    name: '🪵 Cabinwood Fireplace Hearth',
    category: 'polaroid',
    backgroundType: 'gradient',
    backgroundColor: 'linear-gradient(180deg, #faf5f0 0%, #f4eae1 100%)',
    fontFamily: 'Inter',
    textColor: '#78350f',
    borderColor: '#e7d4c1',
    borderStyle: 'solid',
    borderRadius: 'xl',
    opacity: 1.0,
    caption: '🪵 COZY cabin LOGS & FLICKERING WOODS 🪵',
    subCaption: 'Wool sweaters and golden hour sparklers',
    brandingText: 'Captured on Arpita Snaps ✨',
    showBranding: true,
    stickers: ['🪵', '🧣', '🏠'],
    stickerPositions: 'sides'
  },
  {
    id: 'p_vintage_map',
    name: '🗺️ Explorer Map Parchment',
    category: 'polaroid',
    backgroundType: 'solid',
    backgroundColor: '#fbf5e6',
    fontFamily: 'Pacifico',
    textColor: '#854d0e',
    borderColor: '#ca8a04',
    borderStyle: 'double',
    borderRadius: 'none',
    opacity: 1.0,
    caption: '🗺️ Wandering together to find sweet islands ⛵',
    subCaption: 'Compass directions pointing home',
    brandingText: 'Journey log by Arpita Snaps',
    showBranding: true,
    stickers: ['🗺️', '⛵', '🧭'],
    stickerPositions: 'corners'
  },
  {
    id: 'p_vinyl_player',
    name: '💿 Acoustic Vinyl Groove',
    category: 'polaroid',
    backgroundType: 'solid',
    backgroundColor: '#18181b',
    fontFamily: 'Space Grotesk',
    textColor: '#e4e4e7',
    borderColor: '#27272a',
    borderStyle: 'solid',
    borderRadius: 'full',
    opacity: 1.0,
    caption: '🎵 TRACK 4: OUR GOLDEN SUMMER CHORUS 🎵',
    subCaption: 'Vinyl scratches and acoustic hums',
    brandingText: 'Sleeve label: Arpita Snaps Record Co.',
    showBranding: true,
    stickers: ['💿', '🎵', '📻'],
    stickerPositions: 'sides'
  },
  {
    id: 'p_classic_beige',
    name: '🌾 Dried Straw Wheat Field',
    category: 'polaroid',
    backgroundType: 'solid',
    backgroundColor: '#faf7f2',
    fontFamily: 'Inter',
    textColor: '#57534e',
    borderColor: '#e7e5e4',
    borderStyle: 'solid',
    borderRadius: 'xl',
    opacity: 1.0,
    caption: '🌾 WIND BLOWING THROUGH THE WHEAT FIELDS 🌾',
    subCaption: 'Aesthetic cottagecore slow moments',
    brandingText: 'Made with 💖 by Arpita',
    showBranding: true,
    stickers: ['🌾', '👒', '🐇'],
    stickerPositions: 'sides'
  },
  {
    id: 'p_ticket_stub_pink',
    name: '🎟️ Cinema Ticket Ribbon',
    category: 'polaroid',
    backgroundType: 'gradient',
    backgroundColor: 'linear-gradient(90deg, #fce7f3 0%, #fbcfe8 100%)',
    fontFamily: 'VT323',
    textColor: '#be185d',
    borderColor: '#ec4899',
    borderStyle: 'dashed',
    borderRadius: 'none',
    opacity: 1.0,
    caption: '🎟️ CUTE ADMISSION TICKET: DOUBLE FEATURE PASS 🎟️',
    subCaption: 'Section: Besties-Only  •  Row 24 Seat A',
    brandingText: 'Box office organizer: Arpita Snaps',
    showBranding: true,
    stickers: ['🎟️', '🍿', '🥤'],
    stickerPositions: 'sides'
  },
  {
    id: 'p_old_typewriter',
    name: '⌨️ Antique Typewriter Ribbon',
    category: 'polaroid',
    backgroundType: 'solid',
    backgroundColor: '#fdfdfd',
    fontFamily: 'Space Grotesk',
    textColor: '#111827',
    borderColor: '#d1d5db',
    borderStyle: 'solid',
    borderRadius: 'none',
    opacity: 1.0,
    caption: 'Dear Bestie, today was written in golden letters of time.',
    subCaption: 'Typed on Remington Standard 16',
    brandingText: 'Signature: Arpita Snaps',
    showBranding: true,
    stickers: ['⌨️', '📜', '🖤'],
    stickerPositions: 'corners'
  },
  {
    id: 'p_lavender_farm',
    name: '🪻 Provence Lavender Basket',
    category: 'polaroid',
    backgroundType: 'gradient',
    backgroundColor: 'linear-gradient(135deg, #faf5ff 0%, #f3e8ff 100%)',
    fontFamily: 'Inter',
    textColor: '#6b21a8',
    borderColor: '#d8b4fe',
    borderStyle: 'solid',
    borderRadius: '3xl',
    opacity: 1.0,
    caption: '🪻 Lavender breeze and chamomile fields 🪻',
    subCaption: 'Fragrant sunset walk memories',
    brandingText: 'Captured on Arpita Snaps ✨',
    showBranding: true,
    stickers: ['🪻', '🐝', '🧺'],
    stickerPositions: 'sides'
  },
  {
    id: 'p_autumn_leaves',
    name: '🍁 Copper Woods Scrapbook',
    category: 'polaroid',
    backgroundType: 'gradient',
    backgroundColor: 'linear-gradient(180deg, #fffbeb 0%, #fff7ed 100%)',
    fontFamily: 'Pacifico',
    textColor: '#c2410c',
    borderColor: '#ffedd5',
    borderStyle: 'solid',
    borderRadius: 'xl',
    opacity: 1.0,
    caption: '🍁 Crisp crimson leaves under our cute boots 🍁',
    subCaption: 'Fireside cozy talks with sweet tea',
    brandingText: 'Made with 💖 by Arpita',
    showBranding: true,
    stickers: ['🍁', '☕', '🧥'],
    stickerPositions: 'corners'
  },

  // --- DREAMY & FAIRY (13 templates) ---
  {
    id: 'd_angelcore_cloud',
    name: '☁ Angelic Sky Harp',
    category: 'dreamy',
    backgroundType: 'gradient',
    backgroundColor: 'linear-gradient(180deg, #f0fdf4 0%, #e0f2fe 100%)',
    fontFamily: 'Fredoka',
    textColor: '#0284c7',
    borderColor: '#bae6fd',
    borderStyle: 'double',
    borderRadius: '3xl',
    opacity: 0.95,
    caption: '👼 ANGEL BRIGHT HEAVENS IN BALLET PINK 👼',
    subCaption: 'Golden halo feathers and baby butterflies',
    brandingText: 'Captured on Arpita Snaps ✨',
    showBranding: true,
    stickers: ['👼', '☁️', '🎀'],
    stickerPositions: 'top_fringe',
    isTrending: true
  },
  {
    id: 'd_dreamcore_space',
    name: '🌌 Surreal Cosmic Eye',
    category: 'dreamy',
    backgroundType: 'gradient',
    backgroundColor: 'linear-gradient(180deg, #1e1b4b 0%, #311042 100%)',
    fontFamily: 'VT323',
    textColor: '#d8b4fe',
    borderColor: '#c084fc',
    borderStyle: 'solid',
    borderRadius: 'none',
    opacity: 1.0,
    caption: '🌌 SURREAL TIMELINE ERROR: TIMETRAVELLER 🌌',
    subCaption: 'Astral projection cozy cloud platform',
    brandingText: 'ASTRA COMPILATION: ARPITA_SNAPS',
    showBranding: true,
    stickers: ['🌙', '👁️', '✨'],
    stickerPositions: 'scattered',
    glowColor: '#c084fc'
  },
  {
    id: 'd_fairycore_moss',
    name: '🧚 Forest Moss Glade',
    category: 'dreamy',
    backgroundType: 'gradient',
    backgroundColor: 'linear-gradient(90deg, #f0fdf4 0%, #dcfce7 100%)',
    fontFamily: 'Pacifico',
    textColor: '#166534',
    borderColor: '#bbf7d0',
    borderStyle: 'dashed',
    borderRadius: '3xl',
    opacity: 1.0,
    caption: '🧚 Woodland fairy rings & glowing mushrooms 🧚',
    subCaption: 'Sprinkled with secret clover dust',
    brandingText: 'Forest Guide: Arpita Snaps 🍀',
    showBranding: true,
    stickers: ['🧚', '🍄', '🍀'],
    stickerPositions: 'sides'
  },
  {
    id: 'd_moonlight_lake',
    name: '🌙 Midnight Opal Ripple',
    category: 'dreamy',
    backgroundType: 'solid',
    backgroundColor: '#0c0a0f',
    fontFamily: 'Space Grotesk',
    textColor: '#c084fc',
    borderColor: '#3b0764',
    borderStyle: 'solid',
    borderRadius: 'xl',
    opacity: 1.0,
    caption: '🌙 BATHING IN MAGICAL OPAL RIPPLES 🌙',
    subCaption: 'Midnight crystal reflections',
    brandingText: 'Made with 💖 by Arpita',
    showBranding: true,
    stickers: ['🌙', '🦢', '🔮'],
    stickerPositions: 'corners',
    glowColor: '#3b0764'
  },
  {
    id: 'd_soft_pastel_dream',
    name: '🦋 Iridescent Silk Wing',
    category: 'dreamy',
    backgroundType: 'gradient',
    backgroundColor: 'linear-gradient(90deg, #fdf2f8 0%, #faf5ff 50%, #f0fdf4 100%)',
    fontFamily: 'Fredoka',
    textColor: '#bd93f9',
    borderColor: '#e8d5ff',
    borderStyle: 'solid',
    borderRadius: '3xl',
    opacity: 0.95,
    caption: '🦋 BRIGHT SHINY CHRYSALIS DREAMS 🦋',
    subCaption: 'Soft peach breeze fluttering along',
    brandingText: 'Captured on Arpita Snaps ✨',
    showBranding: true,
    stickers: ['🦋', '🌸', '💫'],
    stickerPositions: 'sides'
  },
  {
    id: 'd_sunset_glow',
    name: '🌅 Golden Hour Peach Gloss',
    category: 'dreamy',
    backgroundType: 'gradient',
    backgroundColor: 'linear-gradient(95deg, #ffedd5 0%, #fed7aa 50%, #fecdd3 100%)',
    fontFamily: 'Inter',
    textColor: '#ea580c',
    borderColor: '#ffedd5',
    borderStyle: 'none',
    borderRadius: 'xl',
    opacity: 1.0,
    caption: '🌅 BATHED IN PEACH SUNSET GLOW 🌅',
    subCaption: 'Golden dust and warm strawberry clouds',
    brandingText: 'Made with 💖 by Arpita',
    showBranding: true,
    stickers: ['🌅', '🍊', '💫'],
    stickerPositions: 'corners'
  },
  {
    id: 'd_sea_glass',
    name: '🐚 Clear Aquamarine Shell',
    category: 'dreamy',
    backgroundType: 'gradient',
    backgroundColor: 'linear-gradient(180deg, #ecfeff 0%, #cffafe 100%)',
    fontFamily: 'Fredoka',
    textColor: '#0e7490',
    borderColor: '#a5f3fc',
    borderStyle: 'solid',
    borderRadius: '3xl',
    opacity: 0.9,
    caption: '🐚 WASHED AWAY UNTO CLEAR SEA GLASS 🐚',
    subCaption: 'Mermaid pearls and ocean spray splashes',
    brandingText: 'Captured on Arpita Snaps ✨',
    showBranding: true,
    stickers: ['🐚', '🏖️', '🧜‍♀'],
    stickerPositions: 'sides'
  },
  {
    id: 'd_northern_lights',
    name: '🌌 Aurora Borealis Magic',
    category: 'dreamy',
    backgroundType: 'gradient',
    backgroundColor: 'linear-gradient(135deg, #050510 0%, #032a30 50%, #0c1844 100%)',
    fontFamily: 'Space Grotesk',
    textColor: '#a7f3d0',
    borderColor: '#059669',
    borderStyle: 'solid',
    borderRadius: 'none',
    opacity: 1.0,
    caption: '🌌 EXPEDITION TO THE AURORA SKY DUST 🌌',
    subCaption: 'Emerald light curtains dancing in dark space',
    brandingText: 'Polar System: Arpita Snaps',
    showBranding: true,
    stickers: ['🌌', '❄️', '🦌'],
    stickerPositions: 'corners',
    glowColor: '#059669'
  },
  {
    id: 'd_unicorn_spark',
    name: '🦄 Princess Celestia Shine',
    category: 'dreamy',
    backgroundType: 'gradient',
    backgroundColor: 'linear-gradient(180deg, #fdf4ff 0%, #f5e3ff 100%)',
    fontFamily: 'Fredoka',
    textColor: '#b5179e',
    borderColor: '#f0abfc',
    borderStyle: 'double',
    borderRadius: 'full',
    opacity: 1.0,
    caption: '🦄 MAGICAL UNICORN MANE SHINE 🦄',
    subCaption: 'Riding celestial pink shooting stars',
    brandingText: 'Made with 💖 by Arpita',
    showBranding: true,
    stickers: ['🦄', '💖', '🌈'],
    stickerPositions: 'top_fringe'
  },
  {
    id: 'd_dandelion_wish',
    name: '🌾 White Dandelion Fluff',
    category: 'dreamy',
    backgroundType: 'solid',
    backgroundColor: '#f8fafc',
    fontFamily: 'Pacifico',
    textColor: '#64748b',
    borderColor: '#cbd5e1',
    borderStyle: 'dashed',
    borderRadius: 'xl',
    opacity: 1.0,
    caption: 'Make a special wish & blow the seeds away...',
    subCaption: 'Soft white stems floating in the breeze',
    brandingText: 'Captured on Arpita Snaps ✨',
    showBranding: true,
    stickers: ['🌾', '🎈', '💭'],
    stickerPositions: 'sides'
  },
  {
    id: 'd_starry_night',
    name: '🌌 Starry Sky Van Gogh',
    category: 'dreamy',
    backgroundType: 'gradient',
    backgroundColor: 'linear-gradient(180deg, #0f172a 0%, #1e3a8a 100%)',
    fontFamily: 'Space Grotesk',
    textColor: '#fef08a',
    borderColor: '#eab308',
    borderStyle: 'solid',
    borderRadius: '3xl',
    opacity: 1.0,
    caption: '🌌 VAN GOGH STARRY NIGHT SWIRLS 🌌',
    subCaption: 'Golden cypress and indigo vortex magic',
    brandingText: 'Art Album by Arpita Snaps',
    showBranding: true,
    stickers: ['🌌', '⭐', '🌻'],
    stickerPositions: 'corners'
  },
  {
    id: 'd_dreamy_pink_glow',
    name: '🌸 Bubble Blush Sunset',
    category: 'dreamy',
    backgroundType: 'gradient',
    backgroundColor: 'linear-gradient(135deg, #fff1f2 0%, #ffe4e6 50%, #fecdd3 100%)',
    fontFamily: 'Fredoka',
    textColor: '#db2777',
    borderColor: '#fda4af',
    borderStyle: 'solid',
    borderRadius: '3xl',
    opacity: 1.0,
    caption: '🌸 GLOWING PEACH BLOSSOM DREAMS 🌸',
    subCaption: 'Pink mist surrounding our lovely secrets',
    brandingText: 'Captured on Arpita Snaps ✨',
    showBranding: true,
    stickers: ['🌸', '✨', '🎀'],
    stickerPositions: 'sides'
  },
  {
    id: 'd_butterfly_garden',
    name: '🦋 Botanical Orchid Garden',
    category: 'dreamy',
    backgroundType: 'gradient',
    backgroundColor: 'linear-gradient(135deg, #fafaf9 0%, #f3f4f6 100%)',
    fontFamily: 'Pacifico',
    textColor: '#4f46e5',
    borderColor: '#a5b4fc',
    borderStyle: 'solid',
    borderRadius: 'xl',
    opacity: 1.0,
    caption: '🦋 Butterflies resting on crystal orchid petals 🌿',
    subCaption: 'Glass conservatory aesthetic',
    brandingText: 'Botanist: Arpita Snaps 🏷️',
    showBranding: true,
    stickers: ['🦋', '🌿', '💧'],
    stickerPositions: 'corners'
  },

  // --- ROMANTIC & BLUSH (12 templates) ---
  {
    id: 'r_valentine_lace',
    name: '💌 Sweetheart Lace Letter',
    category: 'romantic',
    backgroundType: 'gradient',
    backgroundColor: 'linear-gradient(180deg, #fff1f2 0%, #ffe4e6 100%)',
    fontFamily: 'Pacifico',
    textColor: '#db2777',
    borderColor: '#fda4af',
    borderStyle: 'solid',
    borderRadius: 'xl',
    opacity: 1.0,
    caption: '💌 Be my secret sweetheart forever 💌',
    subCaption: 'Lace details and wax seal stamps',
    brandingText: 'Postmarked: Arpita snaps',
    showBranding: true,
    stickers: ['💌', '💝', '🌹'],
    stickerPositions: 'sides',
    isTrending: true
  },
  {
    id: 'r_heart_chain',
    name: '💖 Pink Crystal Hearts',
    category: 'romantic',
    backgroundType: 'gradient',
    backgroundColor: 'linear-gradient(90deg, #ffe4e6 0%, #ffd1dc 50%, #ffd1dc 100%)',
    fontFamily: 'Fredoka',
    textColor: '#e11d48',
    borderColor: '#fda4af',
    borderStyle: 'double',
    borderRadius: '3xl',
    opacity: 1.0,
    caption: '💖 LOCKED IN A SWEET HEART CHAIN 💖',
    subCaption: 'Sparkling cherry quartz locks & keys',
    brandingText: 'Made with 💖 by Arpita',
    showBranding: true,
    stickers: ['💖', '🔒', '🔑'],
    stickerPositions: 'top_fringe'
  },
  {
    id: 'r_couple_memories',
    name: '💑 Eternal Love Scrapbook',
    category: 'romantic',
    backgroundType: 'solid',
    backgroundColor: '#fffcfc',
    fontFamily: 'Inter',
    textColor: '#991b1b',
    borderColor: '#fca5a5',
    borderStyle: 'solid',
    borderRadius: 'md',
    opacity: 1.0,
    caption: '💑 GROWING SWEET OLD WITH YOU STEP BY STEP 💐',
    subCaption: 'Every day is a beautiful cherry blossom page',
    brandingText: 'Captured on Arpita Snaps ✨',
    showBranding: true,
    stickers: ['💑', '💐', '🏡'],
    stickerPositions: 'sides'
  },
  {
    id: 'r_soulmate_aesthetic',
    name: '💌 Soulmate Diary entry',
    category: 'romantic',
    backgroundType: 'solid',
    backgroundColor: '#ffffff',
    fontFamily: 'Pacifico',
    textColor: '#dc2626',
    borderColor: '#fee2e2',
    borderStyle: 'none',
    borderRadius: '3xl',
    opacity: 1.0,
    caption: 'Found the missing jigsaw piece of my sweet life...',
    subCaption: 'Written with ultimate heart-filled ink',
    brandingText: 'Secret Letter by Arpita Snaps',
    showBranding: true,
    stickers: ['🧩', '❤️‍🔥', '🧸'],
    stickerPositions: 'scattered'
  },
  {
    id: 'r_blush_pink_love',
    name: '🍑 Juicy Peach Hearts',
    category: 'romantic',
    backgroundType: 'gradient',
    backgroundColor: 'linear-gradient(135deg, #fff5f5 0%, #fed7aa 50%, #fecdd3 100%)',
    fontFamily: 'Fredoka',
    textColor: '#be123c',
    borderColor: '#fda4af',
    borderStyle: 'solid',
    borderRadius: '3xl',
    opacity: 1.0,
    caption: '🍑 YOU MAKE MY CHEEKS BLUSH LIKE PEACHES 🍑',
    subCaption: 'Sweet fruit pulp syrup and tiny hugs',
    brandingText: 'Captured on Arpita Snaps ✨',
    showBranding: true,
    stickers: ['🍑', '💖', '🍨'],
    stickerPositions: 'sides'
  },
  {
    id: 'r_roses_gardens',
    name: '🌹 Crimson Rose Conservatory',
    category: 'romantic',
    backgroundType: 'solid',
    backgroundColor: '#fff1f2',
    fontFamily: 'Inter',
    textColor: '#9f1239',
    borderColor: '#fecdd3',
    borderStyle: 'double',
    borderRadius: 'xl',
    opacity: 1.0,
    caption: '🌹 RED VALVET ROSES IN CHERRY GLOSS Bloom 🌹',
    subCaption: 'Thorn details and fresh flower petals',
    brandingText: 'Made with love by Arpita',
    showBranding: true,
    stickers: ['🌹', '🪴', '🍷'],
    stickerPositions: 'corners'
  },
  {
    id: 'r_golden_sunset_love',
    name: '🌅 Sunset Beach Picnic',
    category: 'romantic',
    backgroundType: 'gradient',
    backgroundColor: 'linear-gradient(180deg, #ffedd5 0%, #fecdd3 100%)',
    fontFamily: 'Pacifico',
    textColor: '#db1b5f',
    borderColor: '#ffe4e6',
    borderStyle: 'solid',
    borderRadius: 'xl',
    opacity: 1.0,
    caption: '🌅 Walking on warm wet sand next to you...',
    subCaption: 'Picnic checks, strawberry juice, and salty hair',
    brandingText: 'Captured on Arpita Snaps ✨',
    showBranding: true,
    stickers: ['🌅', '🍉', '🏖️'],
    stickerPositions: 'sides'
  },
  {
    id: 'r_cupid_arrow',
    name: '💘 Lil Cupid Shooting Star',
    category: 'romantic',
    backgroundType: 'solid',
    backgroundColor: '#fffdfd',
    fontFamily: 'Fredoka',
    textColor: '#e11d48',
    borderColor: '#ffe4e6',
    borderStyle: 'dashed',
    borderRadius: 'full',
    opacity: 1.0,
    caption: '💘 CUPIDS ARROW PINNED MY CUTE HEART 👼',
    subCaption: 'Zero escape from this magical romantic beam',
    brandingText: 'Made with 💖 by Arpita',
    showBranding: true,
    stickers: ['👼', '💘', '🏹'],
    stickerPositions: 'corners'
  },
  {
    id: 'r_twilight_midnight',
    name: '🌙 Twilight Romance Gazebo',
    category: 'romantic',
    backgroundType: 'gradient',
    backgroundColor: 'linear-gradient(135deg, #1e1b4b 0%, #431407 100%)',
    fontFamily: 'Space Grotesk',
    textColor: '#fda4af',
    borderColor: '#9d174d',
    borderStyle: 'solid',
    borderRadius: '3xl',
    opacity: 1.0,
    caption: '🌙 TWILIGHT SHADOWS SURROUNDING OUR CHAT 🌙',
    subCaption: 'Dark velvet velvet night and glowing jasmine stars',
    brandingText: 'Album: Arpita Snaps Late Nights',
    showBranding: true,
    stickers: ['🌙', '🕯️', '🍷'],
    stickerPositions: 'sides'
  },
  {
    id: 'r_puffy_stamps',
    name: '💌 Puffy sticker Postcard',
    category: 'romantic',
    backgroundType: 'solid',
    backgroundColor: '#fff8fa',
    fontFamily: 'Fredoka',
    textColor: '#be185d',
    borderColor: '#fce7f3',
    borderStyle: 'solid',
    borderRadius: 'xl',
    opacity: 1.0,
    caption: '💌 STAMPED WITH CUTE PUFFY KISSES 💋',
    subCaption: 'Teddy postman delivered this letter safely',
    brandingText: 'Postal service: Arpita Snaps',
    showBranding: true,
    stickers: ['💌', '💋', '🧸'],
    stickerPositions: 'corners'
  },
  {
    id: 'r_secret_candle',
    name: '🕯️ Midnight Candlelight Waltz',
    category: 'romantic',
    backgroundType: 'solid',
    backgroundColor: '#1c1917',
    fontFamily: 'Pacifico',
    textColor: '#f59e0b',
    borderColor: '#44403c',
    borderStyle: 'solid',
    borderRadius: 'xl',
    opacity: 1.0,
    caption: '✨ Wax droplets and shadow waltzes on the wall...',
    subCaption: 'Our quiet acoustic evening bubble',
    brandingText: 'Captured on Arpita Snaps ✨',
    showBranding: true,
    stickers: ['🕯️', '🥀', '🎷'],
    stickerPositions: 'sides'
  },
  {
    id: 'r_first_date',
    name: '🧁 Pink Frosting Cafe',
    category: 'romantic',
    backgroundType: 'gradient',
    backgroundColor: 'linear-gradient(180deg, #fff5f5 0%, #ffe3e3 100%)',
    fontFamily: 'Fredoka',
    textColor: '#e53e3e',
    borderColor: '#feb2b2',
    borderStyle: 'solid',
    borderRadius: '3xl',
    opacity: 1.0,
    caption: '🧁 FROSTED CHERRY CUPCAKE CAFE DATE 🍒',
    subCaption: 'Sprinkled sugar and sharing milkshakes with two straws',
    brandingText: 'Cafe Log: Arpita Snaps ☕',
    showBranding: true,
    stickers: ['🧁', '🥤', '🍒'],
    stickerPositions: 'scattered'
  },

  // --- FRIENDSHIP & BESTIE (12 templates) ---
  {
    id: 'f_bestie_energy',
    name: '👯 High-Octane Bestie Energy',
    category: 'friendship',
    backgroundType: 'gradient',
    backgroundColor: 'linear-gradient(45deg, #ffd1e8 0%, #d1f7ff 100%)',
    fontFamily: 'Fredoka',
    textColor: '#9d174d',
    borderColor: '#f472b6',
    borderStyle: 'solid',
    borderRadius: '3xl',
    opacity: 1.0,
    caption: '⭐ BESTIE ENERGY POWER LEVEL EXTREME ⭐',
    subCaption: 'Laughing until our stomachs ache together',
    brandingText: 'Made with 💖 by Arpita',
    showBranding: true,
    stickers: ['👯', '💅', '🍬'],
    stickerPositions: 'sides',
    isTrending: true
  },
  {
    id: 'f_chaotic_duo',
    name: '⚡ Cute Double Trouble Chaos',
    category: 'friendship',
    backgroundType: 'solid',
    backgroundColor: '#fafaf9',
    fontFamily: 'VT323',
    textColor: '#1e3a8a',
    borderColor: '#93c5fd',
    borderStyle: 'dashed',
    borderRadius: 'md',
    opacity: 1.0,
    caption: '⚡ WARNING: CHAOTIC DUO ON THE LOOSE ⚡',
    subCaption: 'Blowing up text group chats since 2003',
    brandingText: 'Elite Bestie Crew Arpita Snaps 📟',
    showBranding: true,
    stickers: ['🤡', '⚡', '🎮'],
    stickerPositions: 'scattered'
  },
  {
    id: 'f_soul_sisters',
    name: '👭 Cosmic Soul Sisters',
    category: 'friendship',
    backgroundType: 'gradient',
    backgroundColor: 'linear-gradient(180deg, #f3e8ff 0%, #e8d5ff 100%)',
    fontFamily: 'Pacifico',
    textColor: '#581c87',
    borderColor: '#d8b4fe',
    borderStyle: 'solid',
    borderRadius: '3xl',
    opacity: 1.0,
    caption: '👭 Connected by cosmic starry threads 🪐',
    subCaption: 'Reading each other\'s cute minds from miles away',
    brandingText: 'Captured on Arpita Snaps ✨',
    showBranding: true,
    stickers: ['👭', '🪐', '💫'],
    stickerPositions: 'corners'
  },
  {
    id: 'f_forever_friends',
    name: '💖 Pinky Promise Shield',
    category: 'friendship',
    backgroundType: 'solid',
    backgroundColor: '#fff5f7',
    fontFamily: 'Fredoka',
    textColor: '#db2777',
    borderColor: '#fce7f3',
    borderStyle: 'solid',
    borderRadius: 'full',
    opacity: 1.0,
    caption: '🤙 SWORN PINKY PROMISE FOREVER 🤙',
    subCaption: 'No secrets, no dramas, only ultimate snuggle times',
    brandingText: 'Sworn Allies: Arpita Snaps',
    showBranding: true,
    stickers: ['🤙', '💖', '🧸'],
    stickerPositions: 'sides'
  },
  {
    id: 'f_matching_memories',
    name: '🥋 Matching Bestie Lockets',
    category: 'friendship',
    backgroundType: 'gradient',
    backgroundColor: 'linear-gradient(135deg, #e0f2fe 0%, #f0fdf4 100%)',
    fontFamily: 'Inter',
    textColor: '#0369a1',
    borderColor: '#bae6fd',
    borderStyle: 'solid',
    borderRadius: 'xl',
    opacity: 1.0,
    caption: '🥋 WE MATCH EACH OTHER\'S WEIRD VIBES 🔐',
    subCaption: 'Two bodies, one braincell working fine',
    brandingText: 'Captured on Arpita Snaps ✨',
    showBranding: true,
    stickers: ['🥋', '🔐', '🐶'],
    stickerPositions: 'corners'
  },
  {
    id: 'f_doodle_board',
    name: '🎨 BFF Drawing Board Canvas',
    category: 'friendship',
    backgroundType: 'solid',
    backgroundColor: '#fefefe',
    fontFamily: 'Pacifico',
    textColor: '#0f172a',
    borderColor: '#cbd5e1',
    borderStyle: 'dashed',
    borderRadius: 'none',
    opacity: 1.0,
    caption: '★ BFF doodle wall - Arpita Snaps edition ★',
    subCaption: 'Please sign your cute name with a custom sketch',
    brandingText: 'Curator: Arpita Snaps Gallery',
    showBranding: true,
    stickers: ['🎨', '🛸', '🍕'],
    stickerPositions: 'scattered'
  },
  {
    id: 'f_sleepover',
    name: '🍿 Pillow Fight Sleepover',
    category: 'friendship',
    backgroundType: 'gradient',
    backgroundColor: 'linear-gradient(180deg, #faf5ff 0%, #fae8ff 100%)',
    fontFamily: 'Fredoka',
    textColor: '#701a75',
    borderColor: '#f5d0fe',
    borderStyle: 'solid',
    borderRadius: '3xl',
    opacity: 1.0,
    caption: '🍿 LATE NIGHT PILLOW FIGHT DISPENSARY 🍿',
    subCaption: 'Sharing pastel popcorn, painting nails, listening to zine pop',
    brandingText: 'Made with 💖 by Arpita',
    showBranding: true,
    stickers: ['🍿', '💅', '💤'],
    stickerPositions: 'sides'
  },
  {
    id: 'f_road_trip',
    name: '🚗 Convertible Road Trip',
    category: 'friendship',
    backgroundType: 'solid',
    backgroundColor: '#fffbeb',
    fontFamily: 'Inter',
    textColor: '#b45309',
    borderColor: '#fde68a',
    borderStyle: 'solid',
    borderRadius: 'xl',
    opacity: 1.0,
    caption: '🚗 SUNROOF DOWN & MUSIC BLOWING IN OUR EARS 🚗',
    subCaption: 'Bestie explorer route 101 - no final coordinates needed',
    brandingText: 'Captured on Arpita Snaps ✨',
    showBranding: true,
    stickers: ['🚗', '🕶️', '🗺️'],
    stickerPositions: 'corners'
  },
  {
    id: 'f_bubble_tea_date',
    name: '🧋 Sweet Boba Tea Sip',
    category: 'friendship',
    backgroundType: 'solid',
    backgroundColor: '#fff7ed',
    fontFamily: 'Fredoka',
    textColor: '#c2410c',
    borderColor: '#fed7aa',
    borderStyle: 'dashed',
    borderRadius: 'full',
    opacity: 1.0,
    caption: '🧋 YOU ARE THE SWEET BOBA TO MY MILK TEA 🧋',
    subCaption: 'Puffy tapioca pearl pearls bouncing high',
    brandingText: 'Boba Club: Arpita Snaps 🏷️',
    showBranding: true,
    stickers: ['🧋', '🍡', '🍭'],
    stickerPositions: 'sides'
  },
  {
    id: 'f_cherry_twins',
    name: '🍒 Cherry Double stalk',
    category: 'friendship',
    backgroundType: 'solid',
    backgroundColor: '#fff5f5',
    fontFamily: 'Fredoka',
    textColor: '#9b1c1c',
    borderColor: '#fca5a5',
    borderStyle: 'solid',
    borderRadius: '3xl',
    opacity: 1.0,
    caption: '🍒 TWIN CHERRIES ATTACHED TO THE SAME STALK 🍒',
    subCaption: 'BFF sweetest pairing in the cute orchard',
    brandingText: 'Made with 💖 by Arpita',
    showBranding: true,
    stickers: ['🍒', '🌸', '🍓'],
    stickerPositions: 'corners'
  },
  {
    id: 'f_secret_clubhouse',
    name: '🏠 Secret Tree clubhouse',
    category: 'friendship',
    backgroundType: 'gradient',
    backgroundColor: 'linear-gradient(180deg, #f0fdf4 0%, #ecfdf5 100%)',
    fontFamily: 'VT323',
    textColor: '#15803d',
    borderColor: '#a7f3d0',
    borderStyle: 'double',
    borderRadius: 'md',
    opacity: 1.0,
    caption: '🏠 NO BOYS ALLOWED: SECRET BFF CLUBHOUSE ENTRY 🔑',
    subCaption: 'Strict passcode required: Give fluffy bears',
    brandingText: 'Clubhouse Architect: Arpita Snaps',
    showBranding: true,
    stickers: ['🏠', '🔑', '🧸'],
    stickerPositions: 'sides'
  },
  {
    id: 'f_arcade_partners',
    name: '🎮 Arcade Co-Op Level 2',
    category: 'friendship',
    backgroundType: 'solid',
    backgroundColor: '#111827',
    fontFamily: 'VT323',
    textColor: '#f43f5e',
    borderColor: '#f43f5e',
    borderStyle: 'solid',
    borderRadius: 'none',
    opacity: 1.0,
    caption: '🎮 LEVEL 2: CO-OP ARCADE PARTNERS IN CRIME 👾',
    subCaption: 'Sharing tokens, fighting pixel bunnies together',
    brandingText: 'System dev: Arpita Snaps ✨',
    showBranding: true,
    stickers: ['🎮', '👾', '🥇'],
    stickerPositions: 'corners'
  },

  // --- MINIMAL PREMIUM & GLASS (11 templates) ---
  {
    id: 'm_glass_frosted',
    name: '💎 Premium Frosted Ice Glass',
    category: 'minimal',
    backgroundType: 'glass',
    backgroundColor: 'rgba(255, 255, 255, 0.45)', // frosted ice glass canvas mock style
    fontFamily: 'Space Grotesk',
    textColor: '#0f172a',
    borderColor: 'rgba(255,255,255,0.6)',
    borderStyle: 'solid',
    borderRadius: '3xl',
    opacity: 0.95,
    caption: '✦ MODERN LUXURY GLASSMORPHISM SHELF ✦',
    subCaption: 'Frosted crystal light diffractions',
    brandingText: 'Crafted with premium taste by Arpita Snaps • 🪐',
    showBranding: true,
    stickers: ['💎', '⚪', '✨'],
    stickerPositions: 'sides',
    isTrending: true
  },
  {
    id: 'm_clean_luxury',
    name: '💍 Creamy Satin Silk Luxury',
    category: 'minimal',
    backgroundType: 'solid',
    backgroundColor: '#fafaf9',
    fontFamily: 'Inter',
    textColor: '#1c1917',
    borderColor: '#e7e5e4',
    borderStyle: 'solid',
    borderRadius: 'none',
    opacity: 1.0,
    caption: '💍 SILK TEXTURE & MINIMAL COMPOSITION DIAL 💍',
    subCaption: 'Premium neutral tones for editorial layouts',
    brandingText: 'Signature curation: Arpita Snaps',
    showBranding: true,
    stickers: ['⚪', '💍', '🕊️'],
    stickerPositions: 'corners'
  },
  {
    id: 'm_pastel_neutral',
    name: '🌾 Warm Oat Linen Cream',
    category: 'minimal',
    backgroundType: 'solid',
    backgroundColor: '#f7f5f0',
    fontFamily: 'Inter',
    textColor: '#44403c',
    borderColor: '#e7e5e4',
    borderStyle: 'none',
    borderRadius: 'xl',
    opacity: 1.0,
    caption: '🌾 WARM OAT CREAM LINNEN ATMOSPHERE 🌾',
    subCaption: 'Soft linen curtains blowing in the sun',
    brandingText: 'Made with 💖 by Arpita',
    showBranding: true,
    stickers: ['🌾', '☕', '🕯️'],
    stickerPositions: 'sides'
  },
  {
    id: 'm_midnight_noir',
    name: '🖤 Matte Onyx Leather Noir',
    category: 'minimal',
    backgroundType: 'solid',
    backgroundColor: '#0a0a0c',
    fontFamily: 'Inter',
    textColor: '#ffffff',
    borderColor: '#242427',
    borderStyle: 'solid',
    borderRadius: 'xl',
    opacity: 1.0,
    caption: '🖤 MATTE ONYX EXCLUSIVE PREVIEW SYSTEM 🖤',
    subCaption: 'Pure monochrome high-contrast composition',
    brandingText: 'No. 3/240 Arpita Snaps Premium',
    showBranding: true,
    stickers: ['🔘', '🖤', '✔️'],
    stickerPositions: 'corners'
  },
  {
    id: 'm_celestial_gold',
    name: '☀️ Golden Sand Empress',
    category: 'minimal',
    backgroundType: 'gradient',
    backgroundColor: 'linear-gradient(180deg, #fefbfc 0%, #fff7ed 100%)',
    fontFamily: 'Space Grotesk',
    textColor: '#b45309',
    borderColor: '#fcd34d',
    borderStyle: 'solid',
    borderRadius: '3xl',
    opacity: 1.0,
    caption: '☀️ CHRONOMETER PLATINUM GOLD MATRIX ☀️',
    subCaption: 'Time ticks in golden celestial gears',
    brandingText: 'Captured on Arpita Snaps ✨',
    showBranding: true,
    stickers: ['☀️', '🌟', '🔱'],
    stickerPositions: 'sides'
  },
  {
    id: 'm_sage_leaf',
    name: '🌿 Sage Green Cotton Lawn',
    category: 'minimal',
    backgroundType: 'solid',
    backgroundColor: '#f4f6f4',
    fontFamily: 'Inter',
    textColor: '#2e3c32',
    borderColor: '#d0ddd0',
    borderStyle: 'solid',
    borderRadius: 'xl',
    opacity: 1.0,
    caption: '🌿 DRIED SAGE AND ORGANIC LAWN SILK 🌱',
    subCaption: 'Botanical greenhouse study margin notes',
    brandingText: 'Made with 💖 by Arpita',
    showBranding: true,
    stickers: ['🌿', '🌱', '🤍'],
    stickerPositions: 'sides'
  },
  {
    id: 'm_milky_glass',
    name: '🥛 Cream Sweet Milk Carton',
    category: 'minimal',
    backgroundType: 'gradient',
    backgroundColor: 'linear-gradient(135deg, #ffffff 0%, #f1f5f9 100%)',
    fontFamily: 'Fredoka',
    textColor: '#475569',
    borderColor: '#cbd5e1',
    borderStyle: 'solid',
    borderRadius: 'full',
    opacity: 1.0,
    caption: '🥛 SOFT MILKY CANVAS FOR SWEETER FACES 🥛',
    subCaption: 'Cream milk carton designs and fresh air',
    brandingText: 'Captured on Arpita Snaps ✨',
    showBranding: true,
    stickers: ['🥛', '🐄', '🥣'],
    stickerPositions: 'sides'
  },
  {
    id: 'm_sandstone_dune',
    name: '🏜️ Terracotta Sandstone Clay',
    category: 'minimal',
    backgroundType: 'solid',
    backgroundColor: '#f5ebe0',
    fontFamily: 'Inter',
    textColor: '#835848',
    borderColor: '#e3d5ca',
    borderStyle: 'solid',
    borderRadius: 'none',
    opacity: 1.0,
    caption: '🏜️ SANDSTONE DUNES IN CLAY EARTH TONE 🏜️',
    subCaption: 'Earthy luxury sandstone pottery studio',
    brandingText: 'Curator code: Arpita snaps',
    showBranding: true,
    stickers: ['🌱', '🏺', '🐚'],
    stickerPositions: 'corners'
  },
  {
    id: 'm_breeze_linen',
    name: '🌬️ Fresh Salt Sea Breeze',
    category: 'minimal',
    backgroundType: 'gradient',
    backgroundColor: 'linear-gradient(180deg, #f0f9ff 0%, #ecfeff 100%)',
    fontFamily: 'Space Grotesk',
    textColor: '#0891b2',
    borderColor: '#bae6fd',
    borderStyle: 'solid',
    borderRadius: '3xl',
    opacity: 1.0,
    caption: '🌬️ FRESH COTTON SHEETS DRYING IN THE WIND 🌬️',
    subCaption: 'Clean ocean air drafts blowing by',
    brandingText: 'Captured on Arpita Snaps ✨',
    showBranding: true,
    stickers: ['🌬️', '⚓', '🤍'],
    stickerPositions: 'sides'
  },
  {
    id: 'm_concrete_goth',
    name: '🩶 Industrial Concrete Loft',
    category: 'minimal',
    backgroundType: 'solid',
    backgroundColor: '#f1f1f4',
    fontFamily: 'Space Grotesk',
    textColor: '#3f3f46',
    borderColor: '#d4d4d8',
    borderStyle: 'solid',
    borderRadius: 'none',
    opacity: 1.0,
    caption: '🩶 BRUTALIST CONCRETE BRICKS & LINES 🩶',
    subCaption: 'Studio architect drafting sheet grid 404',
    brandingText: 'Coded by Arpita snaps',
    showBranding: true,
    stickers: ['🔘', '⌨️', '📂'],
    stickerPositions: 'corners'
  },
  {
    id: 'm_soft_peach_skin',
    name: '🍑 Juicy Nectarine Velvet',
    category: 'minimal',
    backgroundType: 'gradient',
    backgroundColor: 'linear-gradient(135deg, #fff7ed 0%, #fff1f2 100%)',
    fontFamily: 'Fredoka',
    textColor: '#c53030',
    borderColor: '#ffedd5',
    borderStyle: 'none',
    borderRadius: '3xl',
    opacity: 1.0,
    caption: '🍑 SOFT PEACH VELVET SKIN & CREAM 🍑',
    subCaption: 'Nectarine orchard picnic blanket memories',
    brandingText: 'Captured on Arpita Snaps ✨',
    showBranding: true,
    stickers: ['🍑', '🍰', '🌸'],
    stickerPositions: 'sides'
  },

  // --- SCRAPBOOK & JOURNAL (12 templates) ---
  {
    id: 's_washi_tape_blue',
    name: '🩹 Patchy Washi Tape Banner',
    category: 'scrapbook',
    backgroundType: 'solid',
    backgroundColor: '#fafaf2',
    fontFamily: 'Pacifico',
    textColor: '#2563eb',
    borderColor: '#93c5fd',
    borderStyle: 'dashed',
    borderRadius: 'none',
    opacity: 1.0,
    caption: '🩹 Taped with starry blue washi tape tape 🩹',
    subCaption: 'Handcrafted sticky paper memories',
    brandingText: 'Notebook No. 7 by Arpita snaps',
    showBranding: true,
    stickers: ['🩹', '✂️', '✏️'],
    stickerPositions: 'sides',
    isTrending: true
  },
  {
    id: 's_vntg_stickers',
    name: '🏷️ Old Vintage Sticker Board',
    category: 'scrapbook',
    backgroundType: 'solid',
    backgroundColor: '#fbfbf4',
    fontFamily: 'VT323',
    textColor: '#2d3748',
    borderColor: '#d1dbbd',
    borderStyle: 'solid',
    borderRadius: 'xl',
    opacity: 1.0,
    caption: '🏷️ RETRO FRUIT CRATE TRADING STICKERS Collect 🏷️',
    subCaption: 'Snail mail postage and antique flower stamps',
    brandingText: 'Made with 💖 by Arpita',
    showBranding: true,
    stickers: ['🏷️', '🏵️', '📮'],
    stickerPositions: 'scattered'
  },
  {
    id: 's_journal_grid',
    name: '📓 Ruled Math Grid Notepad',
    category: 'scrapbook',
    backgroundType: 'solid',
    backgroundColor: '#f8fafc',
    fontFamily: 'Inter',
    textColor: '#1e293b',
    borderColor: '#cbd5e1',
    borderStyle: 'solid',
    borderRadius: 'none',
    opacity: 1.0,
    caption: '✏️ DIARY OF CUTE COMPILATIONS • VOL 3 ✏️',
    subCaption: 'Graph coordinates layout & pencil sketches',
    brandingText: 'Notebook from Arpita snaps stationery',
    showBranding: true,
    stickers: ['📏', '📝', '📎'],
    stickerPositions: 'corners'
  },
  {
    id: 's_handmade_doodle',
    name: '🖍️ Crayon Smiley Doodle Board',
    category: 'scrapbook',
    backgroundType: 'solid',
    backgroundColor: '#fefdf8',
    fontFamily: 'Pacifico',
    textColor: '#000000',
    borderColor: '#fbbf24',
    borderStyle: 'dashed',
    borderRadius: '3xl',
    opacity: 1.0,
    caption: '🖍️ Hand-painted smiley crayon faces on the wall 🖍️',
    subCaption: 'Wax crayon strokes and cute mess',
    brandingText: 'Made with 💖 by Arpita',
    showBranding: true,
    stickers: ['🖍️', '☀️', '🐱'],
    stickerPositions: 'scattered'
  },
  {
    id: 's_parchment_letters',
    name: '📜 Golden Parchment Scroll',
    category: 'scrapbook',
    backgroundType: 'solid',
    backgroundColor: '#fcf6e8',
    fontFamily: 'Space Grotesk',
    textColor: '#451a03',
    borderColor: '#ca8a04',
    borderStyle: 'solid',
    borderRadius: 'none',
    opacity: 1.0,
    caption: '📜 DECREE OF ULTIMATE BFF ROYAL SOVEREIGNTY 📜',
    subCaption: 'Postmarked in the sweet fairy kingdom of besties',
    brandingText: 'Royal seal stamp: Arpita Snaps',
    showBranding: true,
    stickers: ['📜', '👑', '🛡️'],
    stickerPositions: 'corners'
  },
  {
    id: 's_craft_cardboard',
    name: '📦 Brown Cardboard Box Patch',
    category: 'scrapbook',
    backgroundType: 'solid',
    backgroundColor: '#ebdcb9',
    fontFamily: 'Space Grotesk',
    textColor: '#5c452e',
    borderColor: '#cfa87b',
    borderStyle: 'dashed',
    borderRadius: 'md',
    opacity: 1.0,
    caption: '📦 HANDMADE PARCEL POST STICKER CARDBOARD 🏷️',
    subCaption: 'Wrapped with jute string and natural fiber buttons',
    brandingText: 'Captured on Arpita Snaps • Craft Box',
    showBranding: true,
    stickers: ['📦', '🏷️', '🧶'],
    stickerPositions: 'sides'
  },
  {
    id: 's_comic_book',
    name: '💥 retro Comic Book Panel',
    category: 'scrapbook',
    backgroundType: 'solid',
    backgroundColor: '#fffbeb',
    fontFamily: 'VT323',
    textColor: '#dc2626',
    borderColor: '#000000',
    borderStyle: 'solid',
    borderRadius: 'none',
    opacity: 1.0,
    caption: '💥 POW! BAM! EPIC BESTIE COMIC COLLAPSE 💥',
    subCaption: 'Chapter 24: The Golden Slumber Party Action',
    brandingText: 'Illustrator artist: Arpita Snaps 🎨',
    showBranding: true,
    stickers: ['💥', '🗯️', '👊'],
    stickerPositions: 'scattered'
  },
  {
    id: 's_school_rules',
    name: '📏 Yellow School Bus Ruler',
    category: 'scrapbook',
    backgroundType: 'solid',
    backgroundColor: '#fffbeb',
    fontFamily: 'Inter',
    textColor: '#854d0e',
    borderColor: '#eab308',
    borderStyle: 'dashed',
    borderRadius: 'md',
    opacity: 1.0,
    caption: '📏 COMPASS, GEOMETRY DECK, & CUTE ERASERS 📏',
    subCaption: 'Math homework is way cooler with sweet besties',
    brandingText: 'Made with 💖 by Arpita',
    showBranding: true,
    stickers: ['✏️', '🍎', '🚌'],
    stickerPositions: 'sides'
  },
  {
    id: 's_newspaper_clippings',
    name: '📰 Retro Gazette Columns',
    category: 'scrapbook',
    backgroundType: 'solid',
    backgroundColor: '#f1f1ee',
    fontFamily: 'Space Grotesk',
    textColor: '#18181b',
    borderColor: '#71717a',
    borderStyle: 'solid',
    borderRadius: 'none',
    opacity: 1.0,
    caption: '📰 DAILY RETRO GAZETTE: EXCLUSIVE COVER STORY BFF 📰',
    subCaption: 'Reporter files No. 90210  •  Circulation extreme cute level',
    brandingText: 'Chief editor designer: Arpita Snaps ✒️',
    showBranding: true,
    stickers: ['📰', '🕶️', '🎙️'],
    stickerPositions: 'corners'
  },
  {
    id: 's_musical_sheet',
    name: '🎼 Antique Sheet Music stave',
    category: 'scrapbook',
    backgroundType: 'solid',
    backgroundColor: '#faf7ed',
    fontFamily: 'Pacifico',
    textColor: '#332211',
    borderColor: '#ccbbaa',
    borderStyle: 'solid',
    borderRadius: 'xl',
    opacity: 1.0,
    caption: '🎼 Sonata in G major - Sweet Besties Allegro 🎹',
    subCaption: 'Violin staves, piano chords, and harp strings',
    brandingText: 'Captured on Arpita Snaps ✨',
    showBranding: true,
    stickers: ['🎼', '🎹', '🎻'],
    stickerPositions: 'sides'
  },
  {
    id: 's_blueprint_tech',
    name: '📐 Architect Blueprint cyan',
    category: 'scrapbook',
    backgroundType: 'solid',
    backgroundColor: '#0a3a60',
    fontFamily: 'VT323',
    textColor: '#ffffff',
    borderColor: '#38bdf8',
    borderStyle: 'dashed',
    borderRadius: 'none',
    opacity: 1.0,
    caption: '📐 BLUEPRINT DESIGN SHEET: BESTIE FORT CASTLE CO-OP 🏰',
    subCaption: 'Scale ratio: 1:1,000  •  Drafting tool guidelines',
    brandingText: 'Engineer planner signature: Arpita Snaps',
    showBranding: true,
    stickers: ['📐', '🏰', '🛠️'],
    stickerPositions: 'corners'
  },
  {
    id: 's_pressed_flowers',
    name: '🪻 Herbarium Herb Stamp',
    category: 'scrapbook',
    backgroundType: 'solid',
    backgroundColor: '#fffdf9',
    fontFamily: 'Pacifico',
    textColor: '#606e12',
    borderColor: '#eab308',
    borderStyle: 'solid',
    borderRadius: '3xl',
    opacity: 1.0,
    caption: '🪻 Pressed chamomile buds inside our old dictionary...',
    subCaption: 'Dried leaves preserving warm spring secrets forever',
    brandingText: 'Made with love by Arpita',
    showBranding: true,
    stickers: ['🪻', '🌻', '🧺'],
    stickerPositions: 'sides'
  }
];
