export interface FrameTemplate {
  id: string;
  name: string;
  category: string;
  emoji: string;
  color: string;
  isGradient: boolean;
  gradientColors?: string[];
  thickness: number;
  cornerRadius: number;
  borderStyle: 'solid' | 'dashed' | 'double' | 'torn' | '3d' | 'neon' | 'layered';
  texture: 'none' | 'paper' | 'glitter' | 'holographic' | 'gold_foil' | 'chrome' | 'doodle' | 'film';
  opacity: number;
  glowColor?: string;
  glowIntensity?: number;
  shadowDepth?: number;
  stickers?: string[];
  stickerPlacement?: 'corners' | 'top_bottom' | 'sides' | 'scattered' | 'none';
  isTrending?: boolean;
}

export const FRAME_CATEGORIES = [
  { id: 'all', name: 'All Frames', emoji: '🖼️' },
  { id: 'favorites', name: 'My Stars', emoji: '⭐' },
  { id: 'recent', name: 'Recent', emoji: '🩹' },
  { id: 'trending', name: 'Top Trending', emoji: '🔥' },
  { id: 'modern_aesthetic', name: 'Modern & Aesthetic', emoji: '✨' },
  { id: 'vintage_retro', name: 'Vintage & Film', emoji: '🎞️' },
  { id: 'y2k_grunge', name: 'Y2K & Grunge', emoji: '💿' },
  { id: 'cute_kawaii', name: 'Cute & Kawaii', emoji: '🐾' },
  { id: 'party_celebration', name: 'Party & Celebration', emoji: '🎉' },
  { id: 'luxury_foil', name: 'Luxury & Gold Foil', emoji: '👑' },
  { id: 'neon_glitter', name: 'Neon & Glitter', emoji: '🌈' },
  { id: 'seasonal_holiday', name: 'Seasonal & Holiday', emoji: '🎄' },
  { id: 'friendship_love', name: 'Love & Friends', emoji: '💖' },
  { id: 'academic_milestone', name: 'School & Baby Shower', emoji: '🎓' }
];

// Helper to generate a massive high-end collection of 105 customized templates
const basePresets: FrameTemplate[] = [
  // 1. MODERN & AESTHETIC (15 frames)
  {
    id: 'f_default_white',
    name: 'Classic Paper Border',
    category: 'modern_aesthetic',
    emoji: '📄',
    color: '#ffffff',
    isGradient: false,
    thickness: 10,
    cornerRadius: 8,
    borderStyle: 'solid',
    texture: 'paper',
    opacity: 1.0,
    shadowDepth: 4
  },
  {
    id: 'f_minimal_slate',
    name: 'Minimalist Slate',
    category: 'modern_aesthetic',
    emoji: '🖤',
    color: '#334155',
    isGradient: false,
    thickness: 8,
    cornerRadius: 4,
    borderStyle: 'solid',
    texture: 'none',
    opacity: 1.0,
    shadowDepth: 3
  },
  {
    id: 'f_soft_cream',
    name: 'Soft Linen Cream',
    category: 'modern_aesthetic',
    emoji: '🥛',
    color: '#fdfbf7',
    isGradient: false,
    thickness: 14,
    cornerRadius: 16,
    borderStyle: 'double',
    texture: 'paper',
    opacity: 1.0,
    shadowDepth: 5
  },
  {
    id: 'f_cream_dashed',
    name: 'Aesthetic Linen Stitch',
    category: 'modern_aesthetic',
    emoji: '🧵',
    color: '#FAF6EF',
    isGradient: false,
    thickness: 15,
    cornerRadius: 12,
    borderStyle: 'dashed',
    texture: 'paper',
    opacity: 1.0,
    shadowDepth: 4
  },
  {
    id: 'f_pastel_mist',
    name: 'Pastel Mist Gradient',
    category: 'modern_aesthetic',
    emoji: '🌫️',
    color: '#a5b4fc',
    isGradient: true,
    gradientColors: ['#e0e7ff', '#fae8ff'],
    thickness: 12,
    cornerRadius: 14,
    borderStyle: 'solid',
    texture: 'none',
    opacity: 1.0,
    isTrending: true,
    shadowDepth: 6
  },
  {
    id: 'f_sage_leaf',
    name: 'Sage Botanical',
    category: 'modern_aesthetic',
    emoji: '🍃',
    color: '#8fbc8f',
    isGradient: false,
    thickness: 12,
    cornerRadius: 10,
    borderStyle: 'double',
    texture: 'none',
    opacity: 1.0,
    stickers: ['🌿', '🌱'],
    stickerPlacement: 'top_bottom',
    shadowDepth: 4
  },
  {
    id: 'f_editorial_black',
    name: 'Zine Black Frame',
    category: 'modern_aesthetic',
    emoji: '🔳',
    color: '#0f172a',
    isGradient: false,
    thickness: 16,
    cornerRadius: 0,
    borderStyle: 'solid',
    texture: 'none',
    opacity: 1.0,
    shadowDepth: 8
  },
  {
    id: 'f_frosted_glass',
    name: 'Frosted Glass Frame',
    category: 'modern_aesthetic',
    emoji: '🫧',
    color: 'rgba(255,255,255,0.4)',
    isGradient: false,
    thickness: 14,
    cornerRadius: 18,
    borderStyle: 'layered',
    texture: 'none',
    opacity: 0.75,
    glowColor: '#ffffff',
    glowIntensity: 8,
    shadowDepth: 6
  },
  {
    id: 'f_ceramic_pink',
    name: 'Ceramic Arch Pink',
    category: 'modern_aesthetic',
    emoji: '🍶',
    color: '#ffe4e6',
    isGradient: false,
    thickness: 12,
    cornerRadius: 24,
    borderStyle: 'solid',
    texture: 'paper',
    opacity: 1.0,
    shadowDepth: 5
  },
  {
    id: 'f_modern_taupe',
    name: 'Warm Taupe Clay',
    category: 'modern_aesthetic',
    emoji: '🌾',
    color: '#d6cbb3',
    isGradient: false,
    thickness: 10,
    cornerRadius: 6,
    borderStyle: 'solid',
    texture: 'paper',
    opacity: 1.0,
    shadowDepth: 3
  },
  {
    id: 'f_double_navy',
    name: 'Royal Navy Stripe',
    category: 'modern_aesthetic',
    emoji: '🖊️',
    color: '#1e3a8a',
    isGradient: false,
    thickness: 14,
    cornerRadius: 10,
    borderStyle: 'double',
    texture: 'none',
    opacity: 1.0,
    shadowDepth: 4
  },
  {
    id: 'f_terracotta',
    name: 'Terracotta Matte',
    category: 'modern_aesthetic',
    emoji: '🪵',
    color: '#c2410c',
    isGradient: false,
    thickness: 11,
    cornerRadius: 8,
    borderStyle: 'solid',
    texture: 'paper',
    opacity: 1.0,
    shadowDepth: 4
  },
  {
    id: 'f_monochrome_thin',
    name: 'Archivist Fine Charcoal',
    category: 'modern_aesthetic',
    emoji: '✏️',
    color: '#475569',
    isGradient: false,
    thickness: 6,
    cornerRadius: 2,
    borderStyle: 'solid',
    texture: 'none',
    opacity: 1.0,
    shadowDepth: 2
  },
  {
    id: 'f_matcha_tea',
    name: 'Matcha Whip Cream',
    category: 'modern_aesthetic',
    emoji: '🍵',
    color: '#ecfdf5',
    isGradient: true,
    gradientColors: ['#f0fdf4', '#d1fae5'],
    thickness: 15,
    cornerRadius: 20,
    borderStyle: 'solid',
    texture: 'none',
    opacity: 1.0,
    shadowDepth: 4
  },
  {
    id: 'f_ivory_gilded',
    name: 'Vintage Ivory Gilded',
    category: 'modern_aesthetic',
    emoji: '🕯️',
    color: '#fefefe',
    isGradient: false,
    thickness: 14,
    cornerRadius: 14,
    borderStyle: '3d',
    texture: 'paper',
    opacity: 1.0,
    shadowDepth: 7
  },

  // 2. VINTAGE & RETRO / FILM (15 frames)
  {
    id: 'f_kodak_film',
    name: '1970 Film Strip',
    category: 'vintage_retro',
    emoji: '🎞️',
    color: '#ffb900',
    isGradient: false,
    thickness: 20,
    cornerRadius: 4,
    borderStyle: 'solid',
    texture: 'film',
    opacity: 1.0,
    isTrending: true,
    shadowDepth: 6
  },
  {
    id: 'f_fuji_grain',
    name: 'Fuji Cine Frame',
    category: 'vintage_retro',
    emoji: '📺',
    color: '#059669',
    isGradient: false,
    thickness: 18,
    cornerRadius: 6,
    borderStyle: 'solid',
    texture: 'film',
    opacity: 1.0,
    shadowDepth: 5
  },
  {
    id: 'f_noir_film',
    name: 'Noir Cine sprocket',
    category: 'vintage_retro',
    emoji: '🕶️',
    color: '#111827',
    isGradient: false,
    thickness: 22,
    cornerRadius: 0,
    borderStyle: 'solid',
    texture: 'film',
    opacity: 1.0,
    shadowDepth: 7
  },
  {
    id: 'f_vintage_sepia',
    name: 'Damp Paper Sepia',
    category: 'vintage_retro',
    emoji: '📜',
    color: '#e5d3b3',
    isGradient: false,
    thickness: 15,
    cornerRadius: 12,
    borderStyle: 'torn',
    texture: 'paper',
    opacity: 1.0,
    shadowDepth: 6
  },
  {
    id: 'f_polaroid_bottom',
    name: 'Classic Instant 600',
    category: 'vintage_retro',
    emoji: '📸',
    color: '#ffffff',
    isGradient: false,
    thickness: 14,
    cornerRadius: 8,
    borderStyle: '3d',
    texture: 'paper',
    isTrending: true,
    opacity: 1.0,
    shadowDepth: 6
  },
  {
    id: 'f_parchment',
    name: '1880 Ink Parchment',
    category: 'vintage_retro',
    emoji: '🧭',
    color: '#f1e6cf',
    isGradient: false,
    thickness: 16,
    cornerRadius: 0,
    borderStyle: 'torn',
    texture: 'paper',
    opacity: 1.0,
    shadowDepth: 5
  },
  {
    id: 'f_super_8',
    name: 'Super 8 Projector',
    category: 'vintage_retro',
    emoji: '📽️',
    color: '#180f0a',
    isGradient: false,
    thickness: 18,
    cornerRadius: 16,
    borderStyle: 'solid',
    texture: 'film',
    opacity: 1.0,
    shadowDepth: 6
  },
  {
    id: 'f_victorian',
    name: 'Victorian Gilt Wood',
    category: 'vintage_retro',
    emoji: '🏰',
    color: '#b45309',
    isGradient: false,
    thickness: 16,
    cornerRadius: 4,
    borderStyle: '3d',
    texture: 'none',
    opacity: 1.0,
    glowColor: '#eab308',
    glowIntensity: 4,
    shadowDepth: 8
  },
  {
    id: 'f_scrapbook_tape',
    name: 'Scrapbook Washi Frame',
    category: 'vintage_retro',
    emoji: '🩹',
    color: '#fed7aa',
    isGradient: false,
    thickness: 12,
    cornerRadius: 12,
    borderStyle: 'layered',
    texture: 'paper',
    opacity: 1.0,
    stickers: ['🩹', '📌'],
    stickerPlacement: 'top_bottom',
    shadowDepth: 4
  },
  {
    id: 'f_rustic_copper',
    name: 'Rustic Copper Frame',
    category: 'vintage_retro',
    emoji: '🏺',
    color: '#7c2d12',
    isGradient: false,
    thickness: 12,
    cornerRadius: 6,
    borderStyle: '3d',
    texture: 'none',
    opacity: 1.0,
    shadowDepth: 5
  },
  {
    id: 'f_news_print',
    name: 'Zine Newspaper clipping',
    category: 'vintage_retro',
    emoji: '📰',
    color: '#f8fafc',
    isGradient: false,
    thickness: 14,
    cornerRadius: 0,
    borderStyle: 'dashed',
    texture: 'paper',
    opacity: 1.0,
    stickers: ['✂️', '✍️'],
    stickerPlacement: 'sides',
    shadowDepth: 4
  },
  {
    id: 'f_gothic_lace',
    name: 'Gothic Black Lace',
    category: 'vintage_retro',
    emoji: '🕸️',
    color: '#09090b',
    isGradient: false,
    thickness: 15,
    cornerRadius: 15,
    borderStyle: 'double',
    texture: 'paper',
    opacity: 1.0,
    stickers: ['🕷️', '🕸️'],
    stickerPlacement: 'corners',
    shadowDepth: 5
  },
  {
    id: 'f_burnt_edge',
    name: 'Burnt Charcoal Vignette',
    category: 'vintage_retro',
    emoji: '🔥',
    color: '#000000',
    isGradient: false,
    thickness: 16,
    cornerRadius: 12,
    borderStyle: 'solid',
    texture: 'film',
    opacity: 0.9,
    shadowDepth: 6
  },
  {
    id: 'f_vhs_tracking',
    name: 'VHS Wave Overlay',
    category: 'vintage_retro',
    emoji: '📼',
    color: '#1e1b4b',
    isGradient: true,
    gradientColors: ['#1e1b4b', '#312e81'],
    thickness: 14,
    cornerRadius: 4,
    borderStyle: 'dashed',
    texture: 'chrome',
    opacity: 1.0,
    shadowDepth: 5
  },
  {
    id: 'f_retro_album',
    name: 'Viny Records Frame',
    category: 'vintage_retro',
    emoji: '💿',
    color: '#090d16',
    isGradient: false,
    thickness: 16,
    cornerRadius: 30,
    borderStyle: 'double',
    texture: 'chrome',
    opacity: 1.0,
    shadowDepth: 7
  },

  // 3. Y2K & GRUNGE (15 frames)
  {
    id: 'f_acid_cyber',
    name: 'Cyber Acid Shock',
    category: 'y2k_grunge',
    emoji: '📟',
    color: '#bef264',
    isGradient: true,
    gradientColors: ['#bef264', '#06b6d4'],
    thickness: 15,
    cornerRadius: 12,
    borderStyle: 'neon',
    texture: 'chrome',
    opacity: 1.0,
    glowColor: '#bef264',
    glowIntensity: 12,
    isTrending: true,
    shadowDepth: 7
  },
  {
    id: 'f_pink_chrome',
    name: 'Y2K Cyber Pink Chrome',
    category: 'y2k_grunge',
    emoji: '💿',
    color: '#fda4af',
    isGradient: true,
    gradientColors: ['#fda4af', '#f472b6', '#a5b4fc'],
    thickness: 14,
    cornerRadius: 14,
    borderStyle: '3d',
    texture: 'chrome',
    opacity: 1.0,
    glowColor: '#f472b6',
    glowIntensity: 8,
    shadowDepth: 6
  },
  {
    id: 'f_liquid_metal',
    name: 'Liquid Metal Foil',
    category: 'y2k_grunge',
    emoji: '🛹',
    color: '#e2e8f0',
    isGradient: true,
    gradientColors: ['#cbd5e1', '#f1f5f9', '#94a3b8'],
    thickness: 14,
    cornerRadius: 10,
    borderStyle: 'layered',
    texture: 'chrome',
    opacity: 1.0,
    isTrending: true,
    shadowDepth: 5
  },
  {
    id: 'f_glitch_vibe',
    name: '3D Glitch Matrix',
    category: 'y2k_grunge',
    emoji: '👾',
    color: '#ff0055',
    isGradient: true,
    gradientColors: ['#ff0055', '#38bdf8', '#00ffcc'],
    thickness: 12,
    cornerRadius: 6,
    borderStyle: 'neon',
    texture: 'none',
    opacity: 1.0,
    glowColor: '#ff0055',
    glowIntensity: 10,
    shadowDepth: 6
  },
  {
    id: 'f_goth_metal',
    name: 'Goth metal Barbwires',
    category: 'y2k_grunge',
    emoji: '⛓️',
    color: '#0f051d',
    isGradient: false,
    thickness: 16,
    cornerRadius: 0,
    borderStyle: 'double',
    texture: 'chrome',
    opacity: 1.0,
    stickers: ['⚔️', '⛓️'],
    stickerPlacement: 'sides',
    shadowDepth: 6
  },
  {
    id: 'f_neon_mesh',
    name: 'Neon Grid Mesh',
    category: 'y2k_grunge',
    emoji: '🎮',
    color: '#1e1b4b',
    isGradient: false,
    thickness: 12,
    cornerRadius: 10,
    borderStyle: 'dashed',
    texture: 'none',
    opacity: 1.0,
    glowColor: '#38bdf8',
    glowIntensity: 8,
    shadowDepth: 4
  },
  {
    id: 'f_flame_hot',
    name: 'Retro hot Flame',
    category: 'y2k_grunge',
    emoji: '🔥',
    color: '#f97316',
    isGradient: true,
    gradientColors: ['#f97316', '#ef4444', '#facc15'],
    thickness: 14,
    cornerRadius: 12,
    borderStyle: 'solid',
    texture: 'none',
    opacity: 1.0,
    glowColor: '#ea580c',
    glowIntensity: 10,
    shadowDepth: 5
  },
  {
    id: 'f_grunge_tape',
    name: 'Torn Grunge Duct-tape',
    category: 'y2k_grunge',
    emoji: '🎫',
    color: '#1c1917',
    isGradient: false,
    thickness: 15,
    cornerRadius: 2,
    borderStyle: 'torn',
    texture: 'paper',
    opacity: 1.0,
    stickers: ['🩹', '⚠️'],
    stickerPlacement: 'corners',
    shadowDepth: 4
  },
  {
    id: 'f_graffiti',
    name: 'Graffiti Tag Spray',
    category: 'y2k_grunge',
    emoji: '🎨',
    color: '#e11d48',
    isGradient: true,
    gradientColors: ['#ec4899', '#f43f5e', '#ec4899'],
    thickness: 13,
    cornerRadius: 16,
    borderStyle: 'neon',
    texture: 'chrome',
    opacity: 1.0,
    shadowDepth: 6
  },
  {
    id: 'f_punk_studs',
    name: 'Studded Leather Punk',
    category: 'y2k_grunge',
    emoji: '🎸',
    color: '#262626',
    isGradient: false,
    thickness: 15,
    cornerRadius: 6,
    borderStyle: '3d',
    texture: 'paper',
    opacity: 1.0,
    stickers: ['⭐', '☠️'],
    stickerPlacement: 'corners',
    shadowDepth: 6
  },
  {
    id: 'f_cyber_grid',
    name: 'Lime Cyber Grid',
    category: 'y2k_grunge',
    emoji: '💻',
    color: '#022c22',
    isGradient: false,
    thickness: 14,
    cornerRadius: 8,
    borderStyle: 'dashed',
    texture: 'none',
    opacity: 1.0,
    glowColor: '#10b981',
    glowIntensity: 8,
    shadowDepth: 4
  },
  {
    id: 'f_stars_scattered',
    name: 'Aerosol Sparkle Grunge',
    category: 'y2k_grunge',
    emoji: '🌟',
    color: '#4a1d96',
    isGradient: true,
    gradientColors: ['#4a0e4e', '#581c87'],
    thickness: 12,
    cornerRadius: 12,
    borderStyle: 'solid',
    texture: 'glitter',
    opacity: 1.0,
    stickers: ['🩹', '🛸'],
    stickerPlacement: 'sides',
    shadowDepth: 5
  },
  {
    id: 'f_purple_laser',
    name: 'Cyber Laser Beam',
    category: 'y2k_grunge',
    emoji: '🔮',
    color: '#d946ef',
    isGradient: false,
    thickness: 12,
    cornerRadius: 16,
    borderStyle: 'neon',
    texture: 'chrome',
    opacity: 1.0,
    glowColor: '#d946ef',
    glowIntensity: 12,
    shadowDepth: 5
  },
  {
    id: 'f_checkerboard_black',
    name: 'Vans Checkerboard Punk',
    category: 'y2k_grunge',
    emoji: '🏁',
    color: '#2d3748',
    isGradient: false,
    thickness: 16,
    cornerRadius: 10,
    borderStyle: 'solid',
    texture: 'none',
    opacity: 1.0,
    shadowDepth: 6
  },
  {
    id: 'f_leopard_punk',
    name: 'Leopard Print Punk',
    category: 'y2k_grunge',
    emoji: '🐅',
    color: '#78350f',
    isGradient: true,
    gradientColors: ['#fbbf24', '#b45309'],
    thickness: 15,
    cornerRadius: 14,
    borderStyle: 'double',
    texture: 'paper',
    opacity: 1.0,
    shadowDepth: 5
  },

  // 4. CUTE & KAWAII (15 frames)
  {
    id: 'f_puffy_bunny',
    name: 'Puffy Bunny Clouds',
    category: 'cute_kawaii',
    emoji: '🐰',
    color: '#fff1f2',
    isGradient: true,
    gradientColors: ['#ffe4e6', '#fff5f5'],
    thickness: 18,
    cornerRadius: 28,
    borderStyle: 'solid',
    texture: 'paper',
    isTrending: true,
    opacity: 1.0,
    stickers: ['🐰', '🌸', '☁️'],
    stickerPlacement: 'corners',
    shadowDepth: 6
  },
  {
    id: 'f_strawberry_cream',
    name: 'Strawberry Milk Boba',
    category: 'cute_kawaii',
    emoji: '🍓',
    color: '#fecdd3',
    isGradient: true,
    gradientColors: ['#ffe4e6', '#ffd1dc'],
    thickness: 15,
    cornerRadius: 22,
    borderStyle: 'dashed',
    texture: 'paper',
    opacity: 1.0,
    stickers: ['🍓', '🍒'],
    stickerPlacement: 'sides',
    shadowDepth: 4
  },
  {
    id: 'f_teddy_honey',
    name: 'Honey Bear Swells',
    category: 'cute_kawaii',
    emoji: '🧸',
    color: '#fef3c7',
    isGradient: false,
    thickness: 16,
    cornerRadius: 20,
    borderStyle: 'double',
    texture: 'paper',
    opacity: 1.0,
    stickers: ['🧸', '🍯'],
    stickerPlacement: 'corners',
    shadowDepth: 5
  },
  {
    id: 'f_peach_garden',
    name: 'Juicy Garden Peach',
    category: 'cute_kawaii',
    emoji: '🍑',
    color: '#ffedd5',
    isGradient: true,
    gradientColors: ['#ffeedd', '#fed7aa'],
    thickness: 14,
    cornerRadius: 16,
    borderStyle: 'solid',
    texture: 'paper',
    opacity: 1.0,
    stickers: ['🍑', '🌱'],
    stickerPlacement: 'top_bottom',
    shadowDepth: 4
  },
  {
    id: 'f_pompom_yellow',
    name: 'Kawaii Sunshine Puddles',
    category: 'cute_kawaii',
    emoji: '🍮',
    color: '#fef08a',
    isGradient: false,
    thickness: 15,
    cornerRadius: 24,
    borderStyle: 'solid',
    texture: 'none',
    opacity: 1.0,
    stickers: ['🍮', '🍳'],
    stickerPlacement: 'sides',
    shadowDepth: 4
  },
  {
    id: 'f_sakura_blossom',
    name: 'Blooming Sakura Petals',
    category: 'cute_kawaii',
    emoji: '🌸',
    color: '#ffb7d5',
    isGradient: true,
    gradientColors: ['#fff1f2', '#fbcfe8'],
    thickness: 14,
    cornerRadius: 18,
    borderStyle: 'double',
    texture: 'paper',
    opacity: 1.0,
    stickers: ['🌸', '💮'],
    stickerPlacement: 'corners',
    shadowDepth: 4
  },
  {
    id: 'f_sweet_melody',
    name: 'Pink Velvet Melody',
    category: 'cute_kawaii',
    emoji: '🎀',
    color: '#f472b6',
    isGradient: false,
    thickness: 16,
    cornerRadius: 25,
    borderStyle: 'layered',
    texture: 'paper',
    opacity: 1.0,
    isTrending: true,
    stickers: ['🎀', '✨', '🍼'],
    stickerPlacement: 'corners',
    shadowDepth: 6
  },
  {
    id: 'f_shiba_cookie',
    name: 'Golden Shiba Cookie',
    category: 'cute_kawaii',
    emoji: '🐕',
    color: '#fed7aa',
    isGradient: false,
    thickness: 14,
    cornerRadius: 14,
    borderStyle: 'solid',
    texture: 'paper',
    opacity: 1.0,
    stickers: ['🐕', '🍪'],
    stickerPlacement: 'top_bottom',
    shadowDepth: 4
  },
  {
    id: 'f_froggy_rain',
    name: 'Lotus Lily Froggy',
    category: 'cute_kawaii',
    emoji: '🐸',
    color: '#d1fae5',
    isGradient: false,
    thickness: 14,
    cornerRadius: 18,
    borderStyle: 'solid',
    texture: 'none',
    opacity: 1.0,
    stickers: ['🐸', '☔', '🍀'],
    stickerPlacement: 'corners',
    shadowDepth: 5
  },
  {
    id: 'f_pastel_unicorn',
    name: 'Dreamy Unicorn Glow',
    category: 'cute_kawaii',
    emoji: '🦄',
    color: '#fae8ff',
    isGradient: true,
    gradientColors: ['#fae8ff', '#e0f2fe', '#ffd1dc'],
    thickness: 15,
    cornerRadius: 20,
    borderStyle: 'neon',
    texture: 'holographic',
    opacity: 1.0,
    glowColor: '#e9d5ff',
    glowIntensity: 8,
    shadowDepth: 5
  },
  {
    id: 'f_bunny_matcha',
    name: 'Green Matcha Bunny',
    category: 'cute_kawaii',
    emoji: '🐰',
    color: '#e8fdf0',
    isGradient: false,
    thickness: 13,
    cornerRadius: 16,
    borderStyle: 'dashed',
    texture: 'paper',
    opacity: 1.0,
    stickers: ['🐰', '🍵'],
    stickerPlacement: 'sides',
    shadowDepth: 4
  },
  {
    id: 'f_tulip_cottage',
    name: 'Tulip Fields Cottage',
    category: 'cute_kawaii',
    emoji: '🌷',
    color: '#ffe4e6',
    isGradient: true,
    gradientColors: ['#fff1f2', '#fce7f3'],
    thickness: 16,
    cornerRadius: 22,
    borderStyle: 'double',
    texture: 'none',
    opacity: 1.0,
    stickers: ['🌷', '🍃'],
    stickerPlacement: 'corners',
    shadowDepth: 5
  },
  {
    id: 'f_kawaii_kitten',
    name: 'Kawaii Kitten Whisker',
    category: 'cute_kawaii',
    emoji: '🐱',
    color: '#ffffff',
    isGradient: false,
    thickness: 15,
    cornerRadius: 20,
    borderStyle: 'solid',
    texture: 'paper',
    opacity: 1.0,
    stickers: ['🐱', '🥛'],
    stickerPlacement: 'sides',
    shadowDepth: 4
  },
  {
    id: 'f_candy_star',
    name: 'Gummy Stars Pastel',
    category: 'cute_kawaii',
    emoji: '🍬',
    color: '#dbeafe',
    isGradient: true,
    gradientColors: ['#dbeafe', '#ffedd5'],
    thickness: 14,
    cornerRadius: 15,
    borderStyle: 'neon',
    texture: 'glitter',
    opacity: 1.0,
    stickers: ['⭐', '🍬'],
    stickerPlacement: 'corners',
    shadowDepth: 5
  },
  {
    id: 'f_boba_bliss',
    name: 'Sweet Boba Bliss',
    category: 'cute_kawaii',
    emoji: '🧋',
    color: '#ffedd5',
    isGradient: false,
    thickness: 15,
    cornerRadius: 12,
    borderStyle: 'solid',
    texture: 'paper',
    opacity: 1.0,
    stickers: ['🧋', '🧸'],
    stickerPlacement: 'top_bottom',
    shadowDepth: 4
  },

  // 5. PARTY & CELEBRATION (10 frames)
  {
    id: 'f_bday_confetti',
    name: 'Birthday Confetti Fun',
    category: 'party_celebration',
    emoji: '🎉',
    color: '#ff007f',
    isGradient: true,
    gradientColors: ['#f87171', '#fbbf24', '#60a5fa'],
    thickness: 16,
    cornerRadius: 16,
    borderStyle: 'solid',
    texture: 'glitter',
    opacity: 1.0,
    isTrending: true,
    stickers: ['🎉', '🎂', '🎈'],
    stickerPlacement: 'corners',
    shadowDepth: 6
  },
  {
    id: 'f_disco_ball',
    name: '70s Silver Disco Ball',
    category: 'party_celebration',
    emoji: '🪩',
    color: '#e2e8f0',
    isGradient: true,
    gradientColors: ['#cbd5e1', '#ffffff', '#64748b'],
    thickness: 14,
    cornerRadius: 8,
    borderStyle: 'neon',
    texture: 'chrome',
    opacity: 1.0,
    glowColor: '#cbd5e1',
    glowIntensity: 10,
    stickers: ['🪩', '✨'],
    stickerPlacement: 'top_bottom',
    shadowDepth: 5
  },
  {
    id: 'f_party_balloons',
    name: 'Slay Pastel Balloons',
    category: 'party_celebration',
    emoji: '🎈',
    color: '#ffe4e6',
    isGradient: true,
    gradientColors: ['#e0f2fe', '#faf5ff', '#ffedd5'],
    thickness: 14,
    cornerRadius: 18,
    borderStyle: 'double',
    texture: 'none',
    opacity: 1.0,
    stickers: ['🎈', '🌈'],
    stickerPlacement: 'corners',
    shadowDepth: 4
  },
  {
    id: 'f_wedding_arch',
    name: 'Blushing Bride Lace',
    category: 'party_celebration',
    emoji: '💒',
    color: '#fffafb',
    isGradient: false,
    thickness: 18,
    cornerRadius: 24,
    borderStyle: 'double',
    texture: 'paper',
    opacity: 1.0,
    stickers: ['💒', '💍', '🕊️'],
    stickerPlacement: 'corners',
    shadowDepth: 5
  },
  {
    id: 'f_fireworks_neon',
    name: 'Midnight Fireworks Blast',
    category: 'party_celebration',
    emoji: '🎆',
    color: '#0f172a',
    isGradient: false,
    thickness: 16,
    cornerRadius: 10,
    borderStyle: 'neon',
    texture: 'none',
    opacity: 1.0,
    glowColor: '#f43f5e',
    glowIntensity: 12,
    stickers: ['🎆', '✨'],
    stickerPlacement: 'sides',
    shadowDepth: 6
  },
  {
    id: 'f_carnival_ferris',
    name: 'Sunset Carnival Ferris',
    category: 'party_celebration',
    emoji: '🎡',
    color: '#ff7e5f',
    isGradient: true,
    gradientColors: ['#ff7e5f', '#feb47b'],
    thickness: 14,
    cornerRadius: 14,
    borderStyle: 'solid',
    texture: 'paper',
    opacity: 1.0,
    stickers: ['🍿', '🎫'],
    stickerPlacement: 'top_bottom',
    shadowDepth: 4
  },
  {
    id: 'f_birthday_candles',
    name: 'Blow out Candidates',
    category: 'party_celebration',
    emoji: '🎂',
    color: '#fef08a',
    isGradient: true,
    gradientColors: ['#fef08a', '#fda4af'],
    thickness: 15,
    cornerRadius: 16,
    borderStyle: 'dashed',
    texture: 'paper',
    opacity: 1.0,
    stickers: ['🎂', '🕯️'],
    stickerPlacement: 'corners',
    shadowDepth: 5
  },
  {
    id: 'f_slay_queens_party',
    name: 'VIP Slumber Sleepover',
    category: 'party_celebration',
    emoji: '🍿',
    color: '#fdf2f8',
    isGradient: false,
    thickness: 16,
    cornerRadius: 20,
    borderStyle: 'solid',
    texture: 'paper',
    opacity: 1.0,
    stickers: ['🍕', '🍿', '🎬'],
    stickerPlacement: 'corners',
    shadowDepth: 4
  },
  {
    id: 'f_wedding_chapel',
    name: 'White Lilies Wedding',
    category: 'party_celebration',
    emoji: '👰',
    color: '#ffffff',
    isGradient: false,
    thickness: 15,
    cornerRadius: 15,
    borderStyle: 'solid',
    texture: 'paper',
    opacity: 1.0,
    stickers: ['🕊️', '💐'],
    stickerPlacement: 'sides',
    shadowDepth: 4
  },
  {
    id: 'f_champagne_cheers',
    name: 'Gilded Champagne Toast',
    category: 'party_celebration',
    emoji: '🥂',
    color: '#1e293b',
    isGradient: false,
    thickness: 14,
    cornerRadius: 6,
    borderStyle: 'solid',
    texture: 'gold_foil',
    opacity: 1.0,
    stickers: ['🥂', '🌟'],
    stickerPlacement: 'corners',
    shadowDepth: 6
  },

  // 6. LUXURY & GOLD FOIL (10 frames)
  {
    id: 'f_gold_leaf',
    name: 'Ancient Gold Leaf',
    category: 'luxury_foil',
    emoji: '🪙',
    color: '#ca8a04',
    isGradient: true,
    gradientColors: ['#eab308', '#ca8a04', '#fef08a'],
    thickness: 16,
    cornerRadius: 4,
    borderStyle: '3d',
    texture: 'gold_foil',
    isTrending: true,
    opacity: 1.0,
    shadowDepth: 8
  },
  {
    id: 'f_black_marble',
    name: 'Black Gilded Marble',
    category: 'luxury_foil',
    emoji: '🏛️',
    color: '#111827',
    isGradient: false,
    thickness: 20,
    cornerRadius: 12,
    borderStyle: 'solid',
    texture: 'gold_foil',
    opacity: 1.0,
    glowColor: '#fbbf24',
    glowIntensity: 6,
    shadowDepth: 9
  },
  {
    id: 'f_rose_quartz',
    name: 'Luxury Rose Quartz',
    category: 'luxury_foil',
    emoji: '💎',
    color: '#ffe4e6',
    isGradient: true,
    gradientColors: ['#fff1f2', '#fecdd3', '#fda4af'],
    thickness: 15,
    cornerRadius: 16,
    borderStyle: 'double',
    texture: 'holographic',
    opacity: 0.95,
    glowColor: '#fbcfe8',
    glowIntensity: 8,
    shadowDepth: 7
  },
  {
    id: 'f_silver_foil',
    name: 'Reflective Silver Foil',
    category: 'luxury_foil',
    emoji: '🥈',
    color: '#cbd5e1',
    isGradient: true,
    gradientColors: ['#cbd5e1', '#ffffff', '#94a3b8'],
    thickness: 14,
    cornerRadius: 6,
    borderStyle: '3d',
    texture: 'chrome',
    opacity: 1.0,
    shadowDepth: 5
  },
  {
    id: 'f_royal_blackout',
    name: 'Matte Royal Velvet',
    category: 'luxury_foil',
    emoji: '🕷️',
    color: '#0a0a0a',
    isGradient: false,
    thickness: 18,
    cornerRadius: 0,
    borderStyle: 'double',
    texture: 'paper',
    opacity: 1.0,
    shadowDepth: 10
  },
  {
    id: 'f_emerald_cut',
    name: 'Emerald Cut Luxury',
    category: 'luxury_foil',
    emoji: '💚',
    color: '#064e3b',
    isGradient: false,
    thickness: 15,
    cornerRadius: 10,
    borderStyle: 'solid',
    texture: 'gold_foil',
    opacity: 1.0,
    shadowDepth: 7
  },
  {
    id: 'f_pearl_bead',
    name: 'Royal Pearl Beads',
    category: 'luxury_foil',
    emoji: '📿',
    color: '#f8fafc',
    isGradient: false,
    thickness: 14,
    cornerRadius: 22,
    borderStyle: 'layered',
    texture: 'paper',
    opacity: 1.0,
    shadowDepth: 6
  },
  {
    id: 'f_sapphire_crown',
    name: 'Imperial Sapphire Wave',
    category: 'luxury_foil',
    emoji: '👑',
    color: '#0f172a',
    isGradient: true,
    gradientColors: ['#1e3a8a', '#172554'],
    thickness: 16,
    cornerRadius: 8,
    borderStyle: 'double',
    texture: 'gold_foil',
    opacity: 1.0,
    shadowDepth: 8
  },
  {
    id: 'f_silk_magenta',
    name: 'Crimson Gilded Silk',
    category: 'luxury_foil',
    emoji: '🍷',
    color: '#4c0519',
    isGradient: false,
    thickness: 15,
    cornerRadius: 4,
    borderStyle: '3d',
    texture: 'gold_foil',
    opacity: 1.0,
    shadowDepth: 7
  },
  {
    id: 'f_metallic_platinum',
    name: 'Bespoke Platinum Frame',
    category: 'luxury_foil',
    emoji: '💎',
    color: '#e2e8f0',
    isGradient: false,
    thickness: 16,
    cornerRadius: 12,
    borderStyle: 'solid',
    texture: 'chrome',
    opacity: 1.0,
    shadowDepth: 6
  },

  // 7. NEON & GLITTER (10 frames)
  {
    id: 'f_glitter_spark',
    name: 'Princess Pink Glitter',
    category: 'neon_glitter',
    emoji: '💖',
    color: '#ff66b2',
    isGradient: true,
    gradientColors: ['#ff66b2', '#ffccf9'],
    thickness: 15,
    cornerRadius: 20,
    borderStyle: 'solid',
    texture: 'glitter',
    isTrending: true,
    opacity: 1.0,
    glowColor: '#ff66b2',
    glowIntensity: 10,
    shadowDepth: 5
  },
  {
    id: 'f_neon_pink_g',
    name: 'Cyber Rave Pink Glow',
    category: 'neon_glitter',
    emoji: '⚡',
    color: '#1e1b4b',
    isGradient: false,
    thickness: 12,
    cornerRadius: 12,
    borderStyle: 'neon',
    texture: 'none',
    opacity: 1.0,
    glowColor: '#ec4899',
    glowIntensity: 14,
    isTrending: true,
    shadowDepth: 5
  },
  {
    id: 'f_hologram_v2',
    name: 'Chroma Holographic Wave',
    category: 'neon_glitter',
    emoji: '🌈',
    color: '#e0f2fe',
    isGradient: true,
    gradientColors: ['#bae6fd', '#f5d0fe', '#c7d2fe'],
    thickness: 14,
    cornerRadius: 15,
    borderStyle: 'solid',
    texture: 'holographic',
    opacity: 1.0,
    glowColor: '#d8b4fe',
    glowIntensity: 8,
    shadowDepth: 5
  },
  {
    id: 'f_candy_neon',
    name: 'Neon Lime Candy',
    category: 'neon_glitter',
    emoji: '🍭',
    color: '#064e3b',
    isGradient: false,
    thickness: 12,
    cornerRadius: 14,
    borderStyle: 'neon',
    texture: 'none',
    opacity: 1.0,
    glowColor: '#10b981',
    glowIntensity: 12,
    shadowDepth: 5
  },
  {
    id: 'f_glitter_aquamarine',
    name: 'Fairy Glitter Aqua',
    category: 'neon_glitter',
    emoji: '🧚',
    color: '#22d3ee',
    isGradient: true,
    gradientColors: ['#22d3ee', '#818cf8'],
    thickness: 14,
    cornerRadius: 16,
    borderStyle: 'solid',
    texture: 'glitter',
    opacity: 1.0,
    glowColor: '#22d3ee',
    glowIntensity: 8,
    shadowDepth: 4
  },
  {
    id: 'f_rainbow_spark',
    name: 'Spectrum Glitter Ribbon',
    category: 'neon_glitter',
    emoji: '🌈',
    color: '#ff7e5f',
    isGradient: true,
    gradientColors: ['#ff007f', '#eab308', '#06b6d4'],
    thickness: 15,
    cornerRadius: 18,
    borderStyle: 'double',
    texture: 'glitter',
    opacity: 1.0,
    shadowDepth: 6
  },
  {
    id: 'f_purple_nebula',
    name: 'Nebula Space Glow',
    category: 'neon_glitter',
    emoji: '🌌',
    color: '#0f051d',
    isGradient: true,
    gradientColors: ['#1e1b4b', '#4c1d95', '#1e1b4b'],
    thickness: 14,
    cornerRadius: 12,
    borderStyle: 'neon',
    texture: 'none',
    opacity: 1.0,
    glowColor: '#8b5cf6',
    glowIntensity: 15,
    shadowDepth: 6
  },
  {
    id: 'f_glitter_obsidian',
    name: 'Stardust Obsidian Black',
    category: 'neon_glitter',
    emoji: '☄️',
    color: '#0f172a',
    isGradient: false,
    thickness: 16,
    cornerRadius: 10,
    borderStyle: 'solid',
    texture: 'glitter',
    opacity: 1.0,
    glowColor: '#ffffff',
    glowIntensity: 4,
    shadowDepth: 7
  },
  {
    id: 'f_rave_cyan',
    name: 'Tokyo Arcade Cyan Neon',
    category: 'neon_glitter',
    emoji: '🗼',
    color: '#080816',
    isGradient: false,
    thickness: 13,
    cornerRadius: 12,
    borderStyle: 'neon',
    texture: 'chrome',
    opacity: 1.0,
    glowColor: '#06b6d4',
    glowIntensity: 12,
    shadowDepth: 5
  },
  {
    id: 'f_hologram_silver',
    name: 'Iridescent Silver Glimmer',
    category: 'neon_glitter',
    emoji: '🔮',
    color: '#f8fafc',
    isGradient: true,
    gradientColors: ['#e2e8f0', '#cbd5e1', '#f1f5f9'],
    thickness: 14,
    cornerRadius: 18,
    borderStyle: 'solid',
    texture: 'holographic',
    opacity: 1.0,
    shadowDepth: 5
  },

  // 8. SEASONAL & HOLIDAY (10 frames)
  {
    id: 'f_halloween_pumpkin',
    name: 'Spooky Halloween Lantern',
    category: 'seasonal_holiday',
    emoji: '🎃',
    color: '#1e0a3b',
    isGradient: false,
    thickness: 16,
    cornerRadius: 14,
    borderStyle: 'solid',
    texture: 'none',
    opacity: 1.0,
    glowColor: '#f97316',
    glowIntensity: 10,
    stickers: ['🎃', '👻', '🕸️'],
    stickerPlacement: 'corners',
    shadowDepth: 6
  },
  {
    id: 'f_holiday_xmas',
    name: 'Cozy Christmas Hearth',
    category: 'seasonal_holiday',
    emoji: '🎄',
    color: '#14532d',
    isGradient: false,
    thickness: 16,
    cornerRadius: 16,
    borderStyle: 'double',
    texture: 'paper',
    isTrending: true,
    opacity: 1.0,
    stickers: ['🎄', '⛄', '🎁'],
    stickerPlacement: 'corners',
    shadowDepth: 5
  },
  {
    id: 'f_candy_cane',
    name: 'Sweet Candy Cane Stitch',
    category: 'seasonal_holiday',
    emoji: '🍬',
    color: '#ef4444',
    isGradient: true,
    gradientColors: ['#ef4444', '#ffffff'],
    thickness: 14,
    cornerRadius: 12,
    borderStyle: 'dashed',
    texture: 'none',
    opacity: 1.0,
    shadowDepth: 4
  },
  {
    id: 'f_vday_cupid',
    name: 'La Petit Cupid Velvet',
    category: 'friendship_love',
    emoji: '💘',
    color: '#f43f5e',
    isGradient: true,
    gradientColors: ['#f43f5e', '#ffe4e6'],
    thickness: 15,
    cornerRadius: 22,
    borderStyle: 'solid',
    texture: 'paper',
    opacity: 1.0,
    stickers: ['🏹', '💘', '👼'],
    stickerPlacement: 'corners',
    shadowDepth: 5
  },
  {
    id: 'f_new_years_spark',
    name: 'Times Square Midnight Spark',
    category: 'seasonal_holiday',
    emoji: '🎆',
    color: '#090515',
    isGradient: false,
    thickness: 18,
    cornerRadius: 10,
    borderStyle: 'neon',
    texture: 'glitter',
    opacity: 1.0,
    glowColor: '#fbbf24',
    glowIntensity: 10,
    stickers: ['🥂', '✨', '🎈'],
    stickerPlacement: 'corners',
    shadowDepth: 8
  },
  {
    id: 'f_autumn_leaves',
    name: 'Crimson Autumn Leaves',
    category: 'seasonal_holiday',
    emoji: '🍂',
    color: '#7c2d12',
    isGradient: true,
    gradientColors: ['#7c2d12', '#b45309'],
    thickness: 14,
    cornerRadius: 12,
    borderStyle: 'double',
    texture: 'paper',
    opacity: 1.0,
    stickers: ['🍁', '🍂'],
    stickerPlacement: 'top_bottom',
    shadowDepth: 4
  },
  {
    id: 'f_summer_sunflower',
    name: 'Summer Sunflowers Golden',
    category: 'seasonal_holiday',
    emoji: '🌻',
    color: '#fef08a',
    isGradient: false,
    thickness: 14,
    cornerRadius: 20,
    borderStyle: 'solid',
    texture: 'paper',
    opacity: 1.0,
    stickers: ['🌻', '🐝'],
    stickerPlacement: 'sides',
    shadowDepth: 4
  },
  {
    id: 'f_cherry_blaze',
    name: 'Blossoming Spring Breeze',
    category: 'seasonal_holiday',
    emoji: '🌸',
    color: '#ffccd5',
    isGradient: true,
    gradientColors: ['#fff0f3', '#ffccd5'],
    thickness: 15,
    cornerRadius: 15,
    borderStyle: 'double',
    texture: 'none',
    opacity: 1.0,
    stickers: ['🌸', '🦋'],
    stickerPlacement: 'corners',
    shadowDepth: 4
  },
  {
    id: 'f_winter_snowman',
    name: 'Snowfall Arctic Frost',
    category: 'seasonal_holiday',
    emoji: '❄️',
    color: '#e0f2fe',
    isGradient: true,
    gradientColors: ['#e0f2fe', '#bae6fd'],
    thickness: 15,
    cornerRadius: 24,
    borderStyle: 'solid',
    texture: 'glitter',
    opacity: 1.0,
    stickers: ['⛄', '❄️'],
    stickerPlacement: 'sides',
    shadowDepth: 4
  },
  {
    id: 'f_witchy_cat',
    name: 'Midnight Witch Black Cat',
    category: 'seasonal_holiday',
    emoji: '🐈',
    color: '#0e0b16',
    isGradient: false,
    thickness: 16,
    cornerRadius: 14,
    borderStyle: 'double',
    texture: 'none',
    opacity: 1.0,
    glowColor: '#a855f7',
    glowIntensity: 8,
    stickers: ['🐈', '🔮', '🦇'],
    stickerPlacement: 'corners',
    shadowDepth: 6
  },

  // 9. LOVE & FRIENDS (10 frames)
  {
    id: 'f_sweet_heart_f',
    name: 'Sweet Hearts Chain',
    category: 'friendship_love',
    emoji: '💖',
    color: '#f43f5e',
    isGradient: true,
    gradientColors: ['#fb7185', '#f43f5e'],
    thickness: 15,
    cornerRadius: 20,
    borderStyle: 'solid',
    texture: 'paper',
    isTrending: true,
    opacity: 1.0,
    stickers: ['💖', '💕', '🥰'],
    stickerPlacement: 'corners',
    shadowDepth: 5
  },
  {
    id: 'f_bestie_polaroid',
    name: 'Cute BFF Forever Ribbon',
    category: 'friendship_love',
    emoji: '👯‍♀️',
    color: '#fed7aa',
    isGradient: true,
    gradientColors: ['#fed7aa', '#fecdd3'],
    thickness: 16,
    cornerRadius: 22,
    borderStyle: 'double',
    texture: 'paper',
    opacity: 1.0,
    isTrending: true,
    stickers: ['👯‍♀️', '💝', '✨'],
    stickerPlacement: 'corners',
    shadowDepth: 5
  },
  {
    id: 'f_secret_love_bubble',
    name: 'Secret Valentine Bow',
    category: 'friendship_love',
    emoji: '💌',
    color: '#ffe4e6',
    isGradient: false,
    thickness: 14,
    cornerRadius: 15,
    borderStyle: 'dashed',
    texture: 'paper',
    opacity: 1.0,
    stickers: ['🎀', '💌', '🍬'],
    stickerPlacement: 'sides',
    shadowDepth: 4
  },
  {
    id: 'f_lipsticks_blush',
    name: 'Blushing Kisses Kiss',
    category: 'friendship_love',
    emoji: '💋',
    color: '#be123c',
    isGradient: true,
    gradientColors: ['#f43f5e', '#be123c'],
    thickness: 15,
    cornerRadius: 12,
    borderStyle: 'solid',
    texture: 'none',
    opacity: 1.0,
    stickers: ['💋', '💄'],
    stickerPlacement: 'corners',
    shadowDepth: 5
  },
  {
    id: 'f_angel_heart',
    name: 'Seraphim Angel Hearts',
    category: 'friendship_love',
    emoji: '👼',
    color: '#f0fdf4',
    isGradient: true,
    gradientColors: ['#f0fdf4', '#e0f2fe'],
    thickness: 14,
    cornerRadius: 24,
    borderStyle: 'double',
    texture: 'none',
    opacity: 1.0,
    stickers: ['👼', '⭐', '🤍'],
    stickerPlacement: 'corners',
    shadowDepth: 4
  },
  {
    id: 'f_cotton_candy_bff',
    name: 'Cotton Candy BFF Clouds',
    category: 'friendship_love',
    emoji: '🍥',
    color: '#dbeafe',
    isGradient: true,
    gradientColors: ['#dbeafe', '#fce7f3'],
    thickness: 15,
    cornerRadius: 18,
    borderStyle: 'solid',
    texture: 'none',
    opacity: 1.0,
    stickers: ['🍥', '🍨'],
    stickerPlacement: 'top_bottom',
    shadowDepth: 4
  },
  {
    id: 'f_pink_checkered_love',
    name: 'Pink Lover Checkboard',
    category: 'friendship_love',
    emoji: '💓',
    color: '#fbcfe8',
    isGradient: false,
    thickness: 16,
    cornerRadius: 14,
    borderStyle: 'solid',
    texture: 'none',
    opacity: 1.0,
    stickers: ['💓', '🎀'],
    stickerPlacement: 'corners',
    shadowDepth: 5
  },
  {
    id: 'f_eternal_spark',
    name: 'Eternal Sparks Matching',
    category: 'friendship_love',
    emoji: '✨',
    color: '#fffbeb',
    isGradient: true,
    gradientColors: ['#fef3c7', '#ffd1e8'],
    thickness: 14,
    cornerRadius: 16,
    borderStyle: 'double',
    texture: 'glitter',
    opacity: 1.0,
    stickers: ['🔗', '💗'],
    stickerPlacement: 'sides',
    shadowDepth: 4
  },
  {
    id: 'f_vintage_lovers',
    name: 'Retro Lovers Sepia',
    category: 'friendship_love',
    emoji: '🥀',
    color: '#eeddbb',
    isGradient: false,
    thickness: 15,
    cornerRadius: 8,
    borderStyle: 'solid',
    texture: 'paper',
    opacity: 1.0,
    stickers: ['🌹', '🍷'],
    stickerPlacement: 'corners',
    shadowDepth: 5
  },
  {
    id: 'f_dream_team_puzzle',
    name: 'Matching BFF Puzzle',
    category: 'friendship_love',
    emoji: '🧩',
    color: '#a5f3fc',
    isGradient: true,
    gradientColors: ['#a5f3fc', '#fbcfe8'],
    thickness: 14,
    cornerRadius: 16,
    borderStyle: 'layered',
    texture: 'none',
    opacity: 1.0,
    stickers: ['🧩', '✨'],
    stickerPlacement: 'top_bottom',
    shadowDepth: 4
  },

  // 10. SCHOOL & BABY SHOWER / MILESTONE (10 frames)
  {
    id: 'f_school_crayons',
    name: 'Creative Back School',
    category: 'academic_milestone',
    emoji: '🎒',
    color: '#eab308',
    isGradient: true,
    gradientColors: ['#fef08a', '#fb7185', '#60a5fa'],
    thickness: 15,
    cornerRadius: 14,
    borderStyle: 'solid',
    texture: 'paper',
    opacity: 1.0,
    stickers: ['🖍️', '✏️', '🍎'],
    stickerPlacement: 'corners',
    shadowDepth: 5
  },
  {
    id: 'f_graduation_cap',
    name: 'Graduate Milestone Class',
    category: 'academic_milestone',
    emoji: '🎓',
    color: '#1e293b',
    isGradient: false,
    thickness: 18,
    cornerRadius: 8,
    borderStyle: 'double',
    texture: 'none',
    opacity: 1.0,
    stickers: ['🎓', '📜', '⭐'],
    stickerPlacement: 'corners',
    shadowDepth: 7
  },
  {
    id: 'f_baby_bottle_p',
    name: 'Cute Baby Shower Pink',
    category: 'academic_milestone',
    emoji: '🍼',
    color: '#fce7f3',
    isGradient: false,
    thickness: 16,
    cornerRadius: 24,
    borderStyle: 'solid',
    texture: 'paper',
    opacity: 1.0,
    stickers: ['🍼', '🧸', '🐣'],
    stickerPlacement: 'corners',
    shadowDepth: 4
  },
  {
    id: 'f_baby_blue_sleepy',
    name: 'Cute Baby Shower Blue',
    category: 'academic_milestone',
    emoji: '🧸',
    color: '#e0f2fe',
    isGradient: false,
    thickness: 16,
    cornerRadius: 24,
    borderStyle: 'solid',
    texture: 'paper',
    opacity: 1.0,
    stickers: ['🍼', '👶', '☁️'],
    stickerPlacement: 'corners',
    shadowDepth: 4
  },
  {
    id: 'f_chalk_board_green',
    name: 'Chalkboard Green Board',
    category: 'academic_milestone',
    emoji: '🏫',
    color: '#064e3b',
    isGradient: false,
    thickness: 15,
    cornerRadius: 6,
    borderStyle: 'dashed',
    texture: 'paper',
    opacity: 1.0,
    stickers: ['📐', '🏫'],
    stickerPlacement: 'top_bottom',
    shadowDepth: 5
  },
  {
    id: 'f_ruled_notebook',
    name: 'Ruled Notebook Grid',
    category: 'academic_milestone',
    emoji: '📓',
    color: '#ffffff',
    isGradient: false,
    thickness: 15,
    cornerRadius: 8,
    borderStyle: 'dashed',
    texture: 'paper',
    opacity: 1.0,
    stickers: ['🖇️', '📝'],
    stickerPlacement: 'sides',
    shadowDepth: 4
  },
  {
    id: 'f_stork_delivering',
    name: 'Sweet Stork Delivery',
    category: 'academic_milestone',
    emoji: '🕊️',
    color: '#fffbfa',
    isGradient: true,
    gradientColors: ['#ffe4e6', '#fff1f2'],
    thickness: 14,
    cornerRadius: 18,
    borderStyle: 'double',
    texture: 'none',
    opacity: 1.0,
    stickers: ['🕊️', '🌸', '👶'],
    stickerPlacement: 'corners',
    shadowDepth: 4
  },
  {
    id: 'f_kinder_block',
    name: 'Wood Block Playground',
    category: 'academic_milestone',
    emoji: '🧱',
    color: '#fbbf24',
    isGradient: true,
    gradientColors: ['#fb923c', '#fbbf24'],
    thickness: 15,
    cornerRadius: 14,
    borderStyle: '3d',
    texture: 'paper',
    opacity: 1.0,
    stickers: ['🎈', '🤡'],
    stickerPlacement: 'sides',
    shadowDepth: 5
  },
  {
    id: 'f_victory_cup',
    name: 'Milestone Golden Cup',
    category: 'academic_milestone',
    emoji: '🏆',
    color: '#fffbeb',
    isGradient: false,
    thickness: 14,
    cornerRadius: 12,
    borderStyle: 'solid',
    texture: 'gold_foil',
    opacity: 1.0,
    stickers: ['🏆', '🏅'],
    stickerPlacement: 'top_bottom',
    shadowDepth: 5
  },
  {
    id: 'f_apple_teacher',
    name: 'Best Teacher Apple',
    category: 'academic_milestone',
    emoji: '🍎',
    color: '#fee2e2',
    isGradient: false,
    thickness: 14,
    cornerRadius: 15,
    borderStyle: 'dashed',
    texture: 'none',
    opacity: 1.0,
    stickers: ['🍎', '🎒'],
    stickerPlacement: 'corners',
    shadowDepth: 4
  }
];

export const PRESET_FRAMES = basePresets;
